### ISSUE TITLE
Theme-Aware MessageBox

### ISSUE THREAD

**Issue by AZProductions** [NaBian/HandyControl#1003]
**Describe the bug**
Hello, I'm wondering, is there a way I can change the theme/colors of a message box. It's pretty annoying to have the color difference even if the window's theme is set dark.

**To Reproduce**

Here's the code for the MessageBox.
```c#
HandyControl.Controls.MessageBox.Show("a new version has been detected!Do you want to update?", "Title", MessageBoxButton.YesNo, MessageBoxImage.Question);
```

Here's the XAML code that I used to change the window theme.

```xaml
xmlns:hc="https://handyorg.github.io/handycontrol"
hc:Theme.Skin="Dark"
```

**Expected behavior**
Note: This is just edited in Photoshop and I want to achieve this result.
![image](https://user-images.githubusercontent.com/66299945/135722716-89546719-d1e1-488f-9ea3-767a1b0ae767.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/66299945/135722541-0927bf3e-1400-4096-8f32-ce2955436972.png)

**Environment (please complete the following information):**
 - .net: 5
 - IDE VS2019
 - Version 3.2.0

**Comment by ghost1372** [comment]
I do not see any problem
![image](https://user-images.githubusercontent.com/9213496/135725011-d33211fe-cbb8-4f21-89c4-67b5cfb72fca.png)

**Comment by AZProductions** [comment]
@ghost1372 I couldn't recreate this, how did you manage to do this?

Did you set the theme in c# code or in xaml? I set it in xaml.

**Comment by ghost1372** [comment]
xaml and c# both working

[HandyControlProject4.zip](https://github.com/HandyOrg/HandyControl/files/7271840/HandyControlProject4.zip)

**Comment by AZProductions** [comment]
Thanks!
