### ISSUE TITLE
System.ArgumentException: ''The Password field is required.' is not a valid value for property 'ErrorStr'.'

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1004]
**Describe the bug**

When you implement the MVVM pattern, is usual to implement the interface INotifyDataErrorInfo. 

```csharp
public interface INotifyDataErrorInfo
{
    bool HasErrors { get; }

    event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;

    IEnumerable GetErrors(string propertyName);
}
```
This interface returns the error of the ViewModel as a non generic `IEnumerable`. By definition, this IEnumerable can contain ANY object, not just `strings`. For example, the Library `Microsoft.Toolkit.Mvvm` implements the interface in the following way:

```csharp
//
// Summary:
//     A base class for objects implementing the System.ComponentModel.INotifyDataErrorInfo
//     interface. This class also inherits from Microsoft.Toolkit.Mvvm.ComponentModel.ObservableObject,
//     so it can be used for observable items too.
public abstract class ObservableValidator : ObservableObject, INotifyDataErrorInfo
{
    public bool HasErrors { get; }

    public event EventHandler<DataErrorsChangedEventArgs>? ErrorsChanged;

    public IEnumerable<ValidationResult> GetErrors(string? propertyName = null);
    
    // Other methods for setting properties and validation
    // [ ... ]
    protected void ValidateAllProperties();

    protected internal void ValidateProperty(object? value, [CallerMemberName] string? propertyName = null);
}
```

This library returns an enumerable of  `System.ComponentModel.DataAnnotations.ValidationResult`. But it could be any object. 
The problem is that in the newer version of HandyControl, all input fields support Validation, but they assume the contents of the `IEnumerable` are strings:

https://github.com/HandyOrg/HandyControl/blob/5dcb6dc64915d66a8bb2f16ba68373587a1fa7ff/src/Shared/HandyControl_Shared/Controls/Input/TextBox.cs#L123-L127

So, this exception is thrown, because `System.ComponentModel.DataAnnotations.ValidationResult` is not a string.

```
System.ArgumentException: ''The Password field is required.' is not a valid value for property 'ErrorStr'.'
```

The correct way, would be: 

```csharp
isError = Validation.GetHasError(this);
if (isError)
{
    SetCurrentValue(ErrorStrProperty, Validation.GetErrors(this)[0].ErrorContent?.ToString());
}
```

**To Reproduce**
Implement `INotifyDataErrorInfo` with `GetErrors` returning an `IEnumerable` of custom error objects instead of `strings` and an exception will be thrown. 

**Environment (please complete the following information):**
 - .net: net5
 - IDE vs2019
 - Version HandyControls 3.3.8 (I use the forked version, but I think this bug report goes here)

**Comment by NaBian** [comment]
I'll deal with it after work on the 13th

**Comment by jhm-ciberman** [comment]
There is no hurry. There is at least one month until we release our software. Thanks for all the amazing work with HandyControl 🎉♥️🙏

**Comment by NaBian** [comment]
If you have a problem next time, you can push a pr without waiting for me. HC is everyone's, not mine.

**Comment by jhm-ciberman** [comment]
Thank you a lot! I will!
