### ISSUE TITLE
Combo Box dropdowns are shifted to the right

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1005]
**Describe the bug**
I updated to the newest version (v3.3.8 in the forked version, not the official repo) and all the ComboBoxes are now shifted to the right.  

Is there any way to make them look good without having to write a custom control template? 

**Screenshots**

![image](https://user-images.githubusercontent.com/7988351/135903019-9389c941-b3ef-4687-911d-a809e43ef721.png)

![image](https://user-images.githubusercontent.com/7988351/135903036-a7a584cc-0e22-4825-bd46-4b762e843a32.png)

![image](https://user-images.githubusercontent.com/7988351/135903052-b18d82f1-d426-4b57-85d3-cc940d147f78.png)

**Environment (please complete the following information):**
 - .net: net5
 - IDE vs2019
 - Version HandyControls 3.3.8 (I use the forked version, but I think this bug report goes here)

Edit: 

Seems related to this commit: https://github.com/HandyOrg/HandyControl/commit/5dcb6dc64915d66a8bb2f16ba68373587a1fa7ff

Any way to revert it or make it optional?

**Comment by NaBian** [comment]
This is obviously a bug, i will fix it.
