### ISSUE TITLE
how to binding ItemSource in WaterfallPanel

### ISSUE THREAD

**Issue by heartacker** [NaBian/HandyControl#1019]
```xml
<hc:ScrollViewer>
    <hc:WaterfallPanel Groups="2" ItemSource={binding something>

      </hc:WaterfallPanel>
</hc:ScrollViewer>
```

**Comment by Yopler** [comment]
There is no `ItemSource` Property in WaterfallPanel.

WaterFallPanel inherited from Panel (see [WaterFallPanel.cs](https://github.com/HandyOrg/HandyControl/blob/master/src/Shared/HandyControl_Shared/Controls/Panel/WaterfallPanel.cs)). See it as a `StackPanel` or a `WrapPanel`.

If you really want to use an `ItemSource` property, you can try this idea : 
```xaml
<ListBox ItemSource="{Binding YourBind}">
     <ListBox.ItemsPanel>
           <ItemPanelTemplate>
                 <hc:WaterFallPanel Groups="2"/>
          </ItemPanelTemplate>
    </ListBox.ItemsPanel>
    <ListBox.ItemTemplate>
         <DataTemplate>
            ...
         </DataTemplate>
   </ListBox.ItemTemplate>
</ListBox>
```

I never try this with the `WaterFallPanel`, but with `StackPanel `it is working. You should give it a try 😄
