### ISSUE TITLE
Growls aren't shown if app is not focused

### ISSUE THREAD

**Issue by Symbai** [NaBian/HandyControl#1020]
**Describe the bug**
In-app growls aren't shown if the app is not the active window. I'm not sure if this is intended but my desire is that they are shown. I use them to display notifications, my app is always on top but not focused. I dont want them to appear on my desktop but within the non focused app. If this is intended, may I ask to provide an additional overload for in-app growl to appear always?

**To Reproduce**
1. Create async method
2. Add delay, after show a growl
3. Launch and set focus to another window

**Expected behavior**
Growl should appear

**Environment (please complete the following information):**
 - .net: 6.0
 - IDE 2022
 - Version 3.2.0

**Additional context**

**Comment by NaBian** [comment]
use Growl.Token to solve your problem

**Comment by Symbai** [comment]
Are you speaking about the XAML `hc:Dialog.Token` ? Because this doesn't fix the issue. Growls are still not shown

**Comment by NaBian** [comment]
hc:Growl.Token

**Comment by Symbai** [comment]
My bad, I'm sorry. But it still doesn't work, this is my code:


```XAML
<hc:Window
          hc: Growl.Token="abc">
    <Grid>
    ...
    </Grid>
</hc:Window>
```

and in code:
```C#
async void Test()
{
	await System.Threading.Tasks.Task.Delay(10000);
	Application.Current.Dispatcher.Invoke(() =>
	{
		Growl.Info("blablablabla", "abc");
	});
}
```
Its only showing up when window has focus

**Comment by Symbai** [comment]
Here is the demonstration GIF, first info growl shows up because window has focus. On second growl I focus another window, no growl shows up this time.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/14368203/137866628-45939aaf-ee74-4d23-aad6-413b7c484a25.gif)

**Comment by Symbai** [comment]
I think its because of this:
https://github.com/HandyOrg/HandyControl/blob/7bf0a1ef3aef8adeac02300c72cd50e2ef4d036e/src/Shared/HandyControl_Shared/Controls/Growl/Growl.cs#L448
should add a check if no window is active, then it uses the default window `Application.Current.Window` if its not null.

**Comment by NaBian** [comment]
you may not have read the document carefully, you must put hc: Growl.Token on Panel not Window:
```
<ScrollViewer VerticalScrollBarVisibility="Hidden" HorizontalAlignment="Right">
    <StackPanel controls:Growl.Token="SuccessMsg" VerticalAlignment="Top" Margin="0,10,10,10"/>
</ScrollViewer>
```

**Comment by NaBian** [comment]
cn: https://handyorg.github.io/handycontrol/extend_controls/growl/
en: https://hosseini.ninja/handycontrol/extend_controls/growl/

**Comment by Symbai** [comment]
> you may not have read the document carefully, you must put hc: Growl.Token on Panel not Window:
> 

Please see the GIF I posted, its from the demo app and in the demo app, `Growl.Token` is on panel. GIF shows it doesn't work.
![image](https://user-images.githubusercontent.com/14368203/137888517-763379a1-6b02-44f4-a50d-01b25cd4beda.png)

 The issue is that if ALL of the application windows are not active, the Growl isn't shown. You can try this yourself, all you need to do is to open GrowlDemoViewModel.cs in VS and change the code to:

```C#
public RelayCommand InfoCmd => new(() => Test());

async void Test()
{
    await System.Threading.Tasks.Task.Delay(5000);
    Application.Current.Dispatcher.Invoke(() =>
    {
        Growl.Info(Properties.Langs.Lang.GrowlInfo, _token);
    });
}
```

Then run the demo app, execute `InfoCmd` and switch to a completely different application, for example Notepad++ or MS Edge or Windows Explorer.

**Comment by NaBian** [comment]
[HandyControlWpfApp3.zip](https://github.com/HandyOrg/HandyControl/files/7373507/HandyControlWpfApp3.zip)

**Comment by Symbai** [comment]
1. Its a .NET Framework project, I said I'm using .NET 6
2. Its using different code, I posted mine twice now. 
3. [WpfApp10.zip](https://github.com/HandyOrg/HandyControl/files/7373925/WpfApp10.zip)

**Comment by ghost1372** [comment]
@Symbai  Does this mean that your problem is solved?

**Comment by CodingOctocat** [comment]
#1497 Growl must be window focused, It's possible to focus manually before show, but it doesn't work if the program is minimized.
