### ISSUE TITLE
Effect效果好像有些渲染方面的问题

### ISSUE THREAD

**Issue by asasn** [NaBian/HandyControl#1021]
win10系统中，给某控件使用Effect="{StaticResource EffectShadow■}"（■为1-5）设置阴影效果，再将其放置在一个gird布局中

该grid把屏幕对半分成两行，同样的控件，同样的设置，放在row0（上半部分），一切正常，放在row1（下半部分），就会虚化，模糊，控件内部的字体渲染呈现出gdi渲染的字体虚化结果。

该场景尚未明确重现条件，但加大排列间距，避免其他控件遮挡等等……都不影响它出现。

环境：
Windows10 1909
.NET Framework 4.7.2 WPF程序

![$9LGKU)06R%5YYFOAEXIB_4](https://user-images.githubusercontent.com/48091517/137892648-6ed2bcc3-8039-4e93-83a1-9b9d883329f1.png)

![6U2MPRVD3546L5SMK@FCE T](https://user-images.githubusercontent.com/48091517/137892292-311ae6cf-a96b-4092-aa79-11b8513da681.png)

**Comment by asasn** [comment]
设计预览的时候，看到的自定义控件也一切正常，调试运行的时候，才能看到字体虚化的结果。

**Comment by NaBian** [comment]
https://stackoverflow.com/questions/21538296/wpf-dropshadow-on-button-causes-blurry-text

**Comment by asasn** [comment]
> https://stackoverflow.com/questions/21538296/wpf-dropshadow-on-button-causes-blurry-text

多谢，已通过`UseLayoutRounding="True"`设置解决了这个问题

暂无能力深究原因，但想起以前玩Windows美化的时候遇到过类似的现象，阴影渲染的范围跨越边界引起……所以我一开始就想通过调整边界来解决，但可能呈现出来的视觉边界和实际边界不一样，还是被渲染了，这个UseLayoutRounding很好的解决了这个问题
