### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by nlogozzo** [NaBian/HandyControl#1040]
There have seem to be a lot of new controls and styles added lately but the nuget package is still on version 3.2.0 released back in June 2021. When can we expect a new version bump with the new features?

**Comment by jhm-ciberman** [comment]
+1 on this. I'm on v3.3.7. I can't update because there are bugs (https://github.com/HandyOrg/HandyControl/issues/1004) in 3.3.8.1 that got fixed in master but they are not released yet. So it would be great to have a new version.

**Comment by NaBian** [comment]
The new version 3.3 will be released on December 4th.
