### ISSUE TITLE
轮播图不支持轮播间隔时间

### ISSUE THREAD

**Issue by mimimiaomiao1** [NaBian/HandyControl#1042]
<hc:Carousel ItemsSource="{Binding imgList}" Margin="32" IsCenter="True" AutoRun="True" Interval="3" Width="600" Height="600" VerticalAlignment="Center">
            <hc:Carousel.ItemTemplate>
                <DataTemplate>
                    <Image Source="{Binding}" />
                </DataTemplate>
            </hc:Carousel.ItemTemplate>
        </hc:Carousel>

设置Interval 没用.

**Comment by NaBian** [comment]
0:0:3
