### ISSUE TITLE
Growl 弹出的气泡捕捉到鼠标导致闪退 V3.2.0

### ISSUE THREAD

**Issue by liujingyang** [NaBian/HandyControl#1043]
**Describe the bug**
Growl 弹出的气泡捕捉到鼠标后闪退

1. 利用Task.Run 调用 Growl，弹出气泡
2. 讲鼠标移动到 气泡上，闪退

**Environment (please complete the following information):**
 - .net: 4.7.2
 - IDE VS2019

**Comment by NaBian** [comment]
Duplicate #867
