### ISSUE TITLE
建议增加Growl在DLL中使用的方法

### ISSUE THREAD

**Issue by ConanNobita** [NaBian/HandyControl#1051]
Growl在Application.Current.Dispatcher.Invoke方法中显示，所以当运行的是一个DLL时，无法使用Growl。运行的DLL不是一个WPF程序，无法获取到Application.Current对象。

**Comment by nicroe1979** [comment]
- @seedtyx

**Comment by ConanNobita** [comment]
DLL是以插件的形式在一个C++的应用中运行，所以无法开启一个Application对象

**Comment by nicroe1979** [comment]
- - - @to

**Comment by nicroe1979** [comment]
```
- - [ ] #> `~~[
]()~~`
```

**Comment by NaBian** [comment]
https://github.com/HandyOrg/HandyControl/issues/603#issuecomment-807992768
