### ISSUE TITLE
如何设置一个较大的圆角按钮

### ISSUE THREAD

**Issue by bitloong** [NaBian/HandyControl#1052]
初次使用，请教一个问题：
想要设置一个较大的圆角按钮：
代码如下：
``` 
<Button Content="Button" Margin="232,267,218,58" Style="{StaticResource ButtonPrimary}" 
                hc:BorderElement.CornerRadius="50"  Height="94" Width="342" />
```
 实际效果如下：
![image](https://user-images.githubusercontent.com/39728119/142986086-7fb5b449-6cc8-46dd-b9e7-405cdce9029c.png)
 
想要达到效果：
![image](https://user-images.githubusercontent.com/39728119/142986185-0be11c54-eb62-4087-ae5f-1bcf4b178fa7.png)

我应该如何设置？
**Environment (please complete the following information):**
 - .net: [4.7.2]
 - IDE [vs2019]
 - Version [3.0.0]

**Comment by Yopler** [comment]
hi 🖐,
I don't read chinese so I translate it. 
I just try your code using the version 3.2 of HandyControl and it work perfectly.
I think you should just update your version of HandyControl. 😉

**Comment by bitloong** [comment]
> hi 🖐, I don't read chinese so I translate it. I just try your code using the version 3.2 of HandyControl and it work perfectly. I think you should just update your version of HandyControl. 😉

hi,thanks very much for your answer. 
I maybe made a low-level mistake.
```
<Grid>
        <Viewbox Stretch="Fill">
            <Button Content="Button1" Margin="215,208,235,117" Style="{StaticResource ButtonPrimary}" 
                hc:BorderElement.CornerRadius="50"  Height="94" Width="342" />
        </Viewbox>
        <Grid>
            <Button Content="Button2" Margin="224,107,226,218" Style="{StaticResource ButtonPrimary}" 
                hc:BorderElement.CornerRadius="50"  Height="94" Width="342" />
        </Grid>
    </Grid>
```
use "Button2": When the window is small size,the button will not be displayed completely.
or we can use "Button1".
