### ISSUE TITLE
[Feature request] PathAnimation

### ISSUE THREAD

**Issue by Symbai** [NaBian/HandyControl#1054]
**Describe the solution you'd like**
I would like to be able to animate a `System.Windows.Shapes.Path` like we can currently do with `System.Windows.Media.Geometry`. Literally all of my icons including icons you can get on for example https://materialdesignicons.com/ are always available using `System.Windows.Shapes.Path`

**Describe alternatives you've considered**
Converting Path data to Geometry data but I don't know how

**Additional context**
I'm not talking about the existing `AnimationPath` control but everything here: https://github.com/HandyOrg/HandyControl/tree/master/src/Shared/HandyControl_Shared/Media/Animation

**Comment by Yopler** [comment]
Hello 🖐,

For your alternative you want to convert Path Data to Geometry ! 
That's pretty easy in fact. 
https://materialdesignicons.com/ give you this, for example : 
```xaml
<Viewbox Width="48" Height="48">
    <Canvas Width="24" Height="24">
        <Path Fill="Black" Data="M6 8C6 5.79 7.79 4 10 4S14 5.79 14 8 12.21 12 10 12 6 10.21 6 8M10 14C5.58 14 2 15.79 2 18V20H13.09C13.04 19.67 13 19.34 13 19C13 17.36 13.66 15.87 14.74 14.78C13.41 14.29 11.78 14 10 14M23 19L20 16V18H16V20H20V22L23 19Z" />
    </Canvas>
</Viewbox>
```

If you want to have a geometry, you just need to copy the `Data` and paste it in a `Geometry` : 
```xaml
<Geometry x:Key="My_Geometry">
<!-- Here your Path Data-->
M6 8C6 5.79 7.79 4 10 4S14 5.79 14 8 12.21 12 10 12 6 10.21 6 8M10 14C5.58 14 2 15.79 2 18V20H13.09C13.04 19.67 13 19.34 13 19C13 17.36 13.66 15.87 14.74 14.78C13.41 14.29 11.78 14 10 14M23 19L20 16V18H16V20H20V22L23 19Z 
</Geometry>
```

Hope this will help you 😄

**Comment by Symbai** [comment]
Sorry but that doesn't work. EasingGeometryKeyFrame etc. is throwing exceptions then.

**Comment by NaBian** [comment]
Shapes must have the same number of points
https://animejs.com/documentation/#morphing
