### ISSUE TITLE
When printing a DataGrid control, it does not show any data. (PrintDialog.PrintVisual)

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1055]
**Describe the bug**
When printing a DataGrid control, it does not show any data.

**To Reproduce**
1. Create a new XAML user control (`MyPrintPageView`)

```xaml
<DataGrid 
    AutoGenerateColumns="True" 
    ItemsSource="{Binding OtherMovementsList}" 
    HorizontalAlignment="Left"/>
```

2. Print the view:
```csharp
PrintDialog printDialog = new PrintDialog();

var print = new MyPrintPageView();
print.DataContext = new MyViewModel();
printDialog.PrintVisual(print, "Printing bug!");
```

3. Execute the app and save the printing as PDF (or print it with an actual printer if you have ink to spare). The DataGrid will show but the content will be empty:

![image](https://user-images.githubusercontent.com/7988351/143881484-f1985167-ebc0-48be-977d-19e7314698cc.png)

Below is a ListView with a GridView as view for comparison: (it renders correctly)

```xaml
<ListView
    ItemsSource="{Binding OtherMovementsList}" 
    HorizontalAlignment="Left">
    <ListView.View>
        <GridView>
            <!-- columns here -->
        </GridView>
    </ListView.View>
</ListView>
```

![image](https://user-images.githubusercontent.com/7988351/143881687-75f89a1e-0cdf-4be6-97bf-7251d43ebb77.png)

Also, here is a comparison for a regular DataGrid with his style set to null. (`Style={x:Null}`). It renders correctly, but it looks awful. 

```xaml
<DataGrid 
    AutoGenerateColumns="True" 
    Style="{x:Null}"
    ItemsSource="{Binding OtherMovementsList}" 
    HorizontalAlignment="Left"/>
```

![image](https://user-images.githubusercontent.com/7988351/143879718-c836cf67-1986-4005-a440-746f50d29d7e.png)

**Expected behavior**
The data grid should render it's content

**Environment (please complete the following information):**
 - .net: Net 5
 - IDE VS2019
 - Version: HandyControls v3.3.7

**Comment by sun2000nian** [comment]
Meeting The Same Trouble On ListView!
Have spent hours on it and not solved

**Comment by jhm-ciberman** [comment]
> Meeting The Same Trouble On ListView! Have spent hours on it and not solved

For me, listview works fine, but it doesn't support star `*` sized columns, so I cannot use it. I ended up building my own table with `<ItemsControl>` with a `<Grid>` inside the ItemTemplate.

**Comment by NaBian** [comment]
I can not reproduce, can you provide a demo?

**Comment by jhm-ciberman** [comment]
Sure! 

Here it is: https://github.com/jhm-ciberman/handycontrols-printing-bug

There are two cases, on screen data grid (without bug) and offscreen data grid (bug)

![image](https://user-images.githubusercontent.com/7988351/144510567-011362ac-14cb-4090-84f8-2be78a9c4a5c.png)

Tell me if you need more details.

**Comment by NaBian** [comment]
the latest code seems to be working fine

**Comment by jhm-ciberman** [comment]
Great! Thank you!

**Comment by ghost1372** [comment]
@jhm-ciberman  I close it, if there is a problem, open it again
