### ISSUE TITLE
[hc:PinBox] How to get password in ViewModel MVVM way?

### ISSUE THREAD

**Issue by NaBian** [NaBian/HandyControl#1064]
### Discussed in https://github.com/HandyOrg/HandyControl/discussions/1036

<div type='discussions-op-text'>

<sup>Originally posted by **GF-Huang** October 30, 2021</sup>
The `hc:PinBox.Password` property is not a `DependencyProperty`.</div>

**Comment by LeoChen98** [comment]
I see this issue was moved to `Done`, so how to?

**Comment by ghost1372** [comment]
> I see this issue was moved to `Done`, so how to?

Sorry, My mistake😅

**Comment by LeoChen98** [comment]
> > I see this issue was moved to `Done`, so how to?
> 
> Sorry, My mistake😅

uh, well, then any solution now?
