### ISSUE TITLE
DateTimePicker sets the Culture to InvariantCulture and breaks any other globalization in the app

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1065]
**Describe the bug**
DateTimePicker sets the culture to InvariantCulture and breaks any other globalization in the app. 

See screenshots below for details.

The problem is caused by this PR: 
https://github.com/HandyOrg/HandyControl/pull/679

This pr adds this line to the constructor of DateTimePicker:
```csharp
Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
```

**To Reproduce**
1. Set the globalization to something other than Invariant culture. For example, this is the code I use in my app to setup the Culture at the start of the application:
```csharp
// Spanish Argentinian culture. The currency sign is the PESOS $ symbol (same as dollars symbol)
CultureInfo culture = (CultureInfo)CultureInfo.GetCultureInfo("es-AR").Clone(); 
Thread.CurrentThread.CurrentUICulture = culture;
Thread.CurrentThread.CurrentCulture = culture;

// Override culture for any thread that will be created after
CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;

// Override culture for XAML Views
FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(
System.Windows.Markup.XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));
```
2 - Then add any thing that requires globalization in the UI thread. For example, using System.Globalization inside XAML: 
```
<!-- xmlns:sysglb="clr-namespace:System.Globalization;assembly=mscorlib" -->

<TextBlock Text="{Binding Amount, StringFormat='C', ConverterCulture={x:Static sysglb:CultureInfo.CurrentCulture}}"/>
```

3 - Then use the `DateTimePicker` anywhere on your app
```
<hc:DateTimePicker
    SelectedDateTime="{Binding DateTime, UpdateSourceTrigger=PropertyChanged}"/>
```

4 - After using the component and reloading the screen, the money format should be showing with the Global currency sign like this `¤ 1234` (https://en.wikipedia.org/wiki/Currency_sign_(typography))

**Expected behavior**
The component should not have this side effect

**Screenshots**
Before opening any screen that uses the DateTimePicker in my app, the culture of the app looks correct:

![image](https://user-images.githubusercontent.com/7988351/144857657-23b51b36-04f2-484c-91dd-83c4ed78559f.png)

When I use the component in my app, all looks okay: 

![image](https://user-images.githubusercontent.com/7988351/144857774-994be3e7-e6a8-447d-a120-302f20a2d9a2.png)

After using the component, the culture is set to invariant culture. All the money format is displayed incorrectly:

![image](https://user-images.githubusercontent.com/7988351/144857985-de55ef1a-da8a-4bfb-9258-96ebc78f935b.png)

**Environment (please complete the following information):**
- .net: Net 5
- IDE VS2019
- Version: HandyControls v3.3.7

**Comment by NaBian** [comment]
@ghost1372 could I trouble you to help me?

**Comment by ghost1372** [comment]
Hi @NaBian, Sure
But These days I am a little busy and I do not have access to my laptop I will try to take a look at it this weekend.

**Comment by ghost1372** [comment]
Hi @NaBian @jhm-ciberman 
This behavior was expected But this behavior has not been managed.😁
The problem occurs when the **<hc:DateTimePicker** is created after the culture is set. DateTimePicker itself, as you mentioned, uses a different culture.
Anyway, I'm trying to find a better solution to this and old issues.

Currently you can use the following solution

`<hc:DateTimePicker Initialized="DateTimePicker_Initialized"/>`

   ```
     private void DateTimePicker_Initialized(object sender, EventArgs e)
        {
            CultureInfo culture = (CultureInfo)CultureInfo.GetCultureInfo("es-AR").Clone();
            Thread.CurrentThread.CurrentCulture = culture;
        }
```

![image](https://user-images.githubusercontent.com/9213496/146605497-1a4cab35-22e8-41b8-aa37-3b4df92cc6bf.png)

**Comment by jhm-ciberman** [comment]
Thank you for the quick response. For the moment, I'm using a combination of two fields in my view model, one for the date and one for the time, and two separate controls in the views, one for the date and one for the date. It is a bit cumbersome to manage, but it's not much problem. I don't want to mess a lot with the culture because my app relies on it in every screen. 

Here is how it currently looks the "Payment method settlement" view. 

![image](https://user-images.githubusercontent.com/7988351/146614849-e1fb2642-5695-46eb-9fb8-cce3806bdd6b.png)
