### ISSUE TITLE
Blue border around TextBox cannot be made transparent.

### ISSUE THREAD

**Issue by ms-somanna** [NaBian/HandyControl#1066]
Once the TextBox has got focus it's BorderBrush changes from gray to blue and remains that way. Even after setting the borderbrush to transparent, the border is still blue.

**Comment by Yopler** [comment]
That the default behavior of the Textbox in HandyControl. Set the borderBrush to transparent will only affect the rest state of the Textbox but not the focus state.

If your don't care about the Border you can simply set `BorderThickness="0"`.

If you want to keep the Border but not have the Border to blue, there is some solution : 
- You can overwrite the `PrimaryBrush` on the TextBox ressources : 
```xaml
<TextBox>
         <TextBox.Resources>
                    <!-- BorderColor is the color of the rest state of the TextBox -->
                    <SolidColorBrush x:Key="PrimaryBrush" Color="{StaticResource BorderColor}"/>
         </TextBox.Resources>
</TextBox>
```

- Create a style that overwrite the `PrimaryBrush`. This way you can apply the same style to all your TextBox
```xaml
<Style x:Key="CustomTextBoxStyle" TargetType="TextBox" BasedOn="{StaticResource TextBoxBaseStyle}">
      <Style.Resources>
                <!-- BorderColor is the color of the rest state of the TextBox -->
                <SolidColorBrush x:Key="PrimaryBrush" Color="{StaticResource BorderColor}"/>
      </Style.Resources>
</Style>
```
then 
```xaml
<TextBox Style="{StaticResource CustomTextBoxStyle}"/>
```

**Comment by Symbai** [comment]
Have you also tried just removing the visual focus style on the textbox directly? `<TextBox FocusVisualStyle="{x:Null}"/>`

**Comment by ms-somanna** [comment]
> Have you also tried just removing the visual focus style on the textbox directly? `<TextBox FocusVisualStyle="{x:Null}"/>`

I'll try that
