### ISSUE TITLE
Make TextBox ContextMenu theme aware.

### ISSUE THREAD

**Issue by ms-somanna** [NaBian/HandyControl#1067]
When dark theme is used, the right-click ContextMenu of textbox has a light background with black foreground. Can we make the ContextMenu to have dark background and white foreground when the dark theme is used?
Also the style of the ContextMenu seems to be the default system base style. Can we change it to use HandyControl style?

**Comment by Yopler** [comment]
Hi 🖐,

I try to add a context menu to a TextBox using the Dark theme of HandyControl. And I don't have any problems.
Can you specify the context of your TextBox ? (Not sur this question is clear 😅)

![image](https://user-images.githubusercontent.com/45144437/145369035-20e6cd44-d7b0-415b-a589-a981bd08e92a.png)

my code :
```xaml
<TextBox Margin="5">
          <TextBox.ContextMenu>
                    <ContextMenu ItemsSource="{Binding MyTree}">
                        <ContextMenu.ItemTemplate>
                            <HierarchicalDataTemplate ItemsSource="{Binding Children}">
                                <TextBlock Text="{Binding Name}"/>
                            </HierarchicalDataTemplate>
                        </ContextMenu.ItemTemplate>
                    </ContextMenu>
         </TextBox.ContextMenu>
</TextBox>
```

```cs
public partial class MainWindow : Window
    {
        public List<MyTreeItem> MyTree { get; set; }

        public MainWindow()
        {
            InitializeComponent();
            DataContext = this;
            MyTree = new List<MyTreeItem>();

            List<MyTreeItem> genericChildren = new List<MyTreeItem>();
            for (int i = 0; i < 4; i++)
                genericChildren.Add( new MyTreeItem($"Item {i}"));

            for (int i = 0; i < 4; i++)
            {
                MyTreeItem item = new MyTreeItem($"Group {i}");
                genericChildren.ForEach(child => child.Parent = item);
                item.Children= genericChildren;
                MyTree.Add(item);
            }
        }
}
```
```cs
public class MyTreeItem
    {
        public string Name { get; set; }
        public List<MyTreeItem> Children { get; set; }

        public MyTreeItem(string name)
        {
            Name = name;
        }
    }
```

**Comment by ms-somanna** [comment]
> Hi 🖐,
> 
> I try to add a context menu to a TextBox using the Dark theme of HandyControl. And I don't have any problems.
> Can you specify the context of your TextBox ? (Not sur this question is clear 😅)
> 
> ![image](https://user-images.githubusercontent.com/45144437/145369035-20e6cd44-d7b0-415b-a589-a981bd08e92a.png)
> 
> my code :
> ```xaml
> <TextBox Margin="5">
>           <TextBox.ContextMenu>
>                     <ContextMenu ItemsSource="{Binding MyTree}">
>                         <ContextMenu.ItemTemplate>
>                             <HierarchicalDataTemplate ItemsSource="{Binding Children}">
>                                 <TextBlock Text="{Binding Name}"/>
>                             </HierarchicalDataTemplate>
>                         </ContextMenu.ItemTemplate>
>                     </ContextMenu>
>          </TextBox.ContextMenu>
> </TextBox>
> ```
> 
> ```cs
> public partial class MainWindow : Window
>     {
>         public List<MyTreeItem> MyTree { get; set; }
> 
>         public MainWindow()
>         {
>             InitializeComponent();
>             DataContext = this;
>             MyTree = new List<MyTreeItem>();
> 
>             List<MyTreeItem> genericChildren = new List<MyTreeItem>();
>             for (int i = 0; i < 4; i++)
>                 genericChildren.Add( new MyTreeItem($"Item {i}"));
> 
>             for (int i = 0; i < 4; i++)
>             {
>                 MyTreeItem item = new MyTreeItem($"Group {i}");
>                 genericChildren.ForEach(child => child.Parent = item);
>                 item.Children= genericChildren;
>                 MyTree.Add(item);
>             }
>         }
> }
> ```
> ```cs
> public class MyTreeItem
>     {
>         public string Name { get; set; }
>         public List<MyTreeItem> Children { get; set; }
> 
>         public MyTreeItem(string name)
>         {
>             Name = name;
>         }
>     }
> ```

I was talking about the default ContextMenu created by the OS for the TextBox and not the one that can be created by us.
If you don't add a custom ContextMenu to your TextBox, the OS will add one. And the one added by the os doesn't follow the theme.

If it is not possible to make the OS's ContextMenu theme aware, atleast can HandyControl be made to handle the default ContextMenu instead of letting the OS handle it. That way the default ContextMenu can be theme aware.

The below image shows the default ContextMenu created by the OS on a TextBox in a HandyControls application. Notice it is not theme aware.
![IMG_20211209_195057851.jpg](https://user-images.githubusercontent.com/32904377/145413894-3e234631-843e-4ffd-b7c3-dab14777b1c7.jpg)

**Comment by Yopler** [comment]
I seem that is not possible ! https://stackoverflow.com/questions/30940939/wpf-default-textbox-contextmenu-styling

But you can create your context menu and apply it to all your `TextBox`. 
Here an example, I found this solution on an forum and adapt it to your problem :
![image](https://user-images.githubusercontent.com/45144437/145416895-bd7dbde1-8742-446d-a91c-9a6dc3e4dd77.png)
```xaml
<ContextMenu x:Key="TextBoxContextMenu">
            <MenuItem Command="ApplicationCommands.Copy" />
            <MenuItem Command="ApplicationCommands.Cut" />
            <MenuItem Command="ApplicationCommands.Paste" />
</ContextMenu>
        
<Style  TargetType="{x:Type TextBox}" BasedOn="{StaticResource TextBoxBaseStyle}">
            <Setter Property="ContextMenu" Value="{StaticResource TextBoxContextMenu}"/>
</Style>
```
Here all the windows commands accessible using AppicationCommands.XXX : https://docs.microsoft.com/fr-fr/dotnet/api/system.windows.input.applicationcommands?view=windowsdesktop-6.0
