### ISSUE TITLE
Win11下使用HandyControl.Controls.MessageBox.Show会导致NullReferenceException异常

### ISSUE THREAD

**Issue by my522cn** [NaBian/HandyControl#1075]
**Describe the bug**
HandyControl.Controls.MessageBox.Show会导致NullReferenceException异常，而使用System.Windows.MessageBox.Show则没有问题。

**To Reproduce**
1. 使用HandyControl插件，创建一个HandyControl App（.net MVVM）项目
2. 添加任意一个Button，并在Click事件中增加HandyControl.Controls.MessageBox.Show("2222");
3. 启动项目并点击这个Button，会抛出NullReferenceException异常。

**Screenshots**
![Snipaste_2021-12-16_16-42-07](https://user-images.githubusercontent.com/11346219/146339111-1bb25535-d54f-45a4-935e-8bc4c64b5bdc.png)

**Environment (please complete the following information):**
 - .net: 6.0
 - IDE vs2022 
 - Version 17.1.0 Preview 1.1

**Comment by NaBian** [comment]
无法复现，请先确认是否加载了样式。

**Comment by my522cn** [comment]
确认加载了样式！使用的是HandyControl VS扩展创建的App

```XMAL
<Application x:Class="HandyControlProject2.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:hc="https://handyorg.github.io/handycontrol"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <hc:ThemeResources/>
                <hc:Theme/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

```

已确认VS2019 Ver16.11.5也会有同样问题，说明和IDE无关。
使用.net 5/6和.net fw 4.8都会出现，说明和.net无关。
使用System.Windows.MessageBox.Show没问题，**Win10下没有问题的，Win11下才出现**。

```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎19/‎11/‎2021
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0
```

如下是Demo [https://github.com/my522cn/HandyControlProject1](https://github.com/my522cn/HandyControlProject1)

**Comment by NaBian** [comment]
你是用的是非官方库，不予以解决。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo ***@***.***&gt;
发送时间: 2021年12月17日 08:53
收件人: HandyOrg/HandyControl ***@***.***&gt;
抄送: NaBian ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[HandyOrg/HandyControl] Win11下使用HandyControl.Controls.MessageBox.Show会导致NullReferenceException异常 (Issue #1075)





 
确认加载了样式！使用的是HandyControl VS扩展创建的App
 <Application x:Class="HandyControlProject2.App"              xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"              xmlns:hc="https://handyorg.github.io/handycontrol"              StartupUri="MainWindow.xaml"&gt;     <Application.Resources&gt;         <ResourceDictionary&gt;             <ResourceDictionary.MergedDictionaries&gt;                 <hc:ThemeResources/&gt;                 <hc:Theme/&gt;             </ResourceDictionary.MergedDictionaries&gt;         </ResourceDictionary&gt;     </Application.Resources&gt; </Application&gt;  
已确认VS2019 Ver16.11.5也会有同样问题，说明和IDE无关。
 使用.net 5/6和.net fw 4.8都会出现，说明和.net无关。
 使用System.Windows.MessageBox.Show没问题，Win10下记得没有是问题的，Win11下才出现。
 EditionWindows 11 Pro Version21H2 Installed on‎19/‎11/‎2021 OS build22000.376 ExperienceWindows Feature Experience Pack 1000.22000.376.0  
如下是Demo https://github.com/my522cn/HandyControlProject1

**Comment by my522cn** [comment]
感谢，收到

**Comment by ghost1372** [comment]
This issue was recently fixed. A new version will be released by the end of the week
https://github.com/ghost1372/HandyControls/issues/105

**Comment by liping94** [comment]
你的资源引用是这么写的？ 没有尝试官方给出的方案？
