### ISSUE TITLE
3.3.0版本Textbox验证失败不变红

### ISSUE THREAD

**Issue by ZhouShuren1881** [NaBian/HandyControl#1086]
**Describe the bug**
最新发布的3.3.0版本Textbox验证失败不变红

**To Reproduce**
1. 在有HandyControl 3.2.0的工程中新建一个Textbox
2. 添加验证规则
3. 运行，触发验证错误，Textbox变红
4. 将HandyControl 升级至3.3.0
5. 再次运行并触发验证失败，Textbox不变红

**Environment (please complete the following information):**
 - .net 5

**Additional context**
非常抱歉，暂时来不及写最小复现场景了。但这个BUG确实是升级之后出现的，降级以后又正常了

**Comment by OxOld** [comment]
所以这个问题处理了吗。目前只有 密码框才可以

**Comment by NaBian** [comment]
修复了
