### ISSUE TITLE
[Feature request]希望可以增加手风琴(Accordion)控件

### ISSUE THREAD

**Issue by LiveIsLive** [NaBian/HandyControl#1097]
类似于这样的
https://blogs.u2u.be/diederik/post/How-to-play-the-Accordion-WPF-Toolkit

**Comment by Yopler** [comment]
Hi 🖐,

Actually a default component of WPF called `<Expander/>` has the same behavior of what you called Accordion.

The only part that doesn't exist in your link exemple is that there is no "AccordionItem". Translate that's not useable with `ItemSource` property. Hwever you can easly create a `ItemsControl` of `Expander` and you will get the same result.

```xaml
<ItemsControl ItemsSource="{Binding YourList}">
          <ItemsControl.ItemTemplate>
                    <DataTemplate>
                            <Expander Header="{Binding YourProperty}">
                                      <Border Background="Aqua" Height="200"/>
                             </Expander>
                    </DataTemplate>
           </ItemsControl.ItemTemplate>
</ItemsControl>
```
![image](https://user-images.githubusercontent.com/45144437/148052045-e5f825ea-9c51-4dc8-87e4-25420e860a92.png)
![image](https://user-images.githubusercontent.com/45144437/148052087-49d284ae-4a5f-4e82-9035-e7ef4ff5ee88.png)

**Comment by LiveIsLive** [comment]
@Yopler The difference is that the height of Expander in your code is fixed, but it should be filled the container if it is a AccordionItem.

**Comment by Yopler** [comment]
@LiveIsLive The height was for the example (same as the first exemple of your link). You can add a paragraph inside or any component of your choice the height will fit the component that are inside your `Expander`.

You should tried by yourself this solution in thee way you want. If it is doesn't match your need, I will be happy to help you ! 😊

**Comment by NaBian** [comment]
[Yopler](https://github.com/Yopler) is right.
