### ISSUE TITLE
Setting Badge control value cause exception

### ISSUE THREAD

**Issue by MohammadRezaKashi** [NaBian/HandyControl#1115]
I defined a badge control in my .xaml file as below code

```
<hc:Badge
            x:Name="hc_Badge"
            Value="10"
            BadgeMargin="0,-14,-20,0"
            Height="30"
            Width="50"
            Margin="32,20,0,0"
            VerticalAlignment="Top"
            Style="{StaticResource BadgeDanger}">
            <Button Content="Error" 
                    Click="ButtonBase_OnClick"/>
</hc:Badge>
```

when I want to set its value like 

`this.hc_Badge.Value = 50;`

in my C# code, it causes an exception 

![errorreport](https://user-images.githubusercontent.com/52103513/151925338-3c0e531a-569c-433d-abde-c1e4060b7fb1.PNG)

**Comment by Yopler** [comment]
hi🖐,

I just try your code and get the same Error. I don't really why the exception is triggered but it's comming form [BadgeBaseStyle.xaml - line 10](https://github.com/HandyOrg/HandyControl/blob/master/src/Shared/HandyControl_Shared/Themes/Styles/Base/BadgeBaseStyle.xaml#L10).

However, I was able to fix the problem. I wait the `Control` to be loaded. 
Here the code :
```cs
public MainWindow()
 {
            InitializeComponent();
            DataContext = this;

            this.Loaded += MainWindow_Loaded;
 }

private void MainWindow_Loaded(object sender, RoutedEventArgs e)
{
            this.hc_Badge.Value++;
}
```

Hope it will help fix your problem 😊
