### ISSUE TITLE
[Bug] CheckComboBox SelectAll not selecting all 

### ISSUE THREAD

**Issue by Yopler** [NaBian/HandyControl#1119]
**Describe the bug**
If in the checkComboBox there is too many item, the SelectAll will select only the visible items. 

**To Reproduce**
You can find the code  here  : #981 

**Expected behavior**
When checking the selectAll , every items need to be selected

**Environment (please complete the following information):**
 - .net: [e.g. 4.8.2]
 - IDE [e.g. vs2019]
 - Version [e.g. 3.3.0]

**Additional context**
On way to solve the pb, is to scale the dropdown to the size of the number of items in it.

**Comment by kababu2021** [comment]
I have seen the same issue. When there's a lot of items, scaling to number of items is not really an option.

**Comment by Yopler** [comment]
Yes ! But for now I need it to work so I scale it big !

**Comment by Mithicor** [comment]
I have seen this too. It seems that until the items are visible on the drop down, the select all button will not grab everything. So If you open the dropdown and scroll all the way down before hitting the "All" button, then it will select all items.

P.S. I have also seen it where if you set items as selected by default, their tags won't show them as selected until you open/close the dropdown.

**Comment by NaBian** [comment]
closed in [7519c7e](https://github.com/HandyOrg/HandyControl/commit/7519c7e93a2efdc98b1064977baa8dc0e2ef6549)
