### ISSUE TITLE
The spanish (es) language was removed in v3.3.10

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1125]
**Describe the bug**
The spanish language (es) was removed in v3.3.11 (not to be confused with the Catalan language) and is not built in nor available as a nuget package

**To Reproduce**
1. Update from v3.3.9 to v3.3.10/v3.3.11 (HandyControls, the forked version)
2. The language spanish is not built in with handy control nor included as a NuGet package (The full list of language pack is [here](https://ghost1372.github.io/handycontrol/langs/#Language-packs)) 

**Expected behavior**
The language was [contributed by me in the past](https://github.com/HandyOrg/HandyControl/issues/959). It would be nice to not be removed. 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - .net: 6.0.200
 - IDE Visual Studio 2022
 - Version v3.3.10 and v3.3.11

**Additional context**
N/A

**Comment by NaBian** [comment]
sorry, i will publish nuget package tomorrow.

**Comment by NaBian** [comment]
done:
https://www.nuget.org/packages/HandyControl.Lang.es/3.3.0

**Comment by jhm-ciberman** [comment]
@NaBian Thank you! It works like a charm. You are amazing!
