### ISSUE TITLE
[Feature request] TabControl 希望能让某个选项卡不允许关闭

### ISSUE THREAD

**Issue by shusongLu** [NaBian/HandyControl#1137]
主页面的Tab不希望能被关闭

**Comment by Yopler** [comment]
Hi 🖐,

I don't understand chinese and using Google trad I don't really understand your request. 
If you are using `hc:TabControl` with property `ShowCloseButton="True"` you will be able to close every `hc:TabItem`.

In the following basic example, You can close every `hc:TabItem`.
```xaml
<hc:TabControl ShowCloseButton="True">
            <hc:TabItem Header="Test"/>
            <hc:TabItem Header="Test"/>
            <hc:TabItem Header="Test"/>
            <hc:TabItem Header="Test"/>
</hc:TabControl>
```

Maybe, if you can give more context, I can help you.

Hope it can help 😊

**Comment by shusongLu** [comment]
> 

Thank you for your answer, what I mean is that some tabs can not be closed, others can be closed

**Comment by NaBian** [comment]
use ShowCloseButton on TabItem

**Comment by shusongLu** [comment]
> use ShowCloseButton on TabItem

不行的,鼠标中键和右键选择关闭都是能关掉的
