### ISSUE TITLE
Used in the WPF HandyControl.Controls.MessageBox Black Windows errors

### ISSUE THREAD

**Issue by wuhaozede** [NaBian/HandyControl#1139]
**Describe the bug**
我使用按钮触发MessageBox，但是它并没有与我预期的一样弹出类似System.Windows.MessageBox类似的窗口，而是出现了巨大的纯黑色窗口。

我使用Snoop查看了MessageBox的属性，发现只有右上角窗口最大化最小化的按钮控件，并没有出现Yes或者No。

希望官方予以解答，我非常强烈的想知道我有什么样的错误。

I use the button to trigger a MessageBox, but it does not like I expected pop-up System. Windows. MessageBox similar window, but a huge black window.

I used Snoop to check the properties of MessageBox and found that there was only the button control for maximizing and minimizing the window in the upper right corner, and No Yes or No appeared.

I hope the official will give an answer, I very strongly want to know what kind of mistake I have.

**To Reproduce**
1. Use 'HandyControl.Cotrols.MessageBox' in MainWindows.cs. I'm going to trigger it using Button.
2. Click on 'Button'
3. See error

**Expected behavior**
The compiler doesn't have any errors, as if it shouldn't

**Screenshots**

**Window that appears**
![image](https://user-images.githubusercontent.com/62633045/158594769-f4cb2fca-2789-4909-bbb1-16c6879aee73.png)

**Snoop**
![image](https://user-images.githubusercontent.com/62633045/158594619-c342268a-f060-4496-b6ce-bdc85e639930.png)

**Environment (please complete the following information):**
 - .Net Framework Version: [4.5] 
 - IDE [vs2019]
 - HandyControl Version [3.3.0.0]

**Comment by wuhaozede** [comment]
`private void Button_Click(object sender, RoutedEventArgs e)
        {
            _ = HandyControl.Controls.MessageBox.Show("Message", "Titel", MessageBoxButton.YesNo, MessageBoxImage.Question, MessageBoxResult.OK);
            _ = System.Windows.MessageBox.Show("Error");
        }`

**Comment by wuhaozede** [comment]
···
private void Button_Click(object sender, RoutedEventArgs e)
        {
            _ = HandyControl.Controls.MessageBox.Show("Message", "Titel", MessageBoxButton.YesNo, MessageBoxImage.Question, MessageBoxResult.OK);
            _ = System.Windows.MessageBox.Show("Error");
        }
···

**Comment by NaBian** [comment]
请确认是否使用样式。

**Comment by wuhaozede** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wuhaozede** [comment]
请问我在哪里使用样式？是使用BaseOn嘛？
![image](https://user-images.githubusercontent.com/62633045/159109511-44781388-9ec9-4c4c-b639-a363400c835f.png)

**Comment by Yopler** [comment]
Hi 🖐,

Make sure that you have import the HandyControl style in your App.xaml !

I have try without the style import and get the same result, so I believe this is a style issue.

To import the HandyControl style you need to add the following part in your App.xaml :
```xaml
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
                <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDark.xaml"/>
                
               <!-- Here the other ResourceDictionary in your App.xaml -->

            </ResourceDictionary.MergedDictionaries>
            
        <!-- Here the other ressources in your App.xaml -->

        </ResourceDictionary>
    </Application.Resources>
```

In the example, I add the Dark style of Handy but you can replace with the light one : `SkinDefault.xaml`

hiope it can help 😊

**Comment by wuhaozede** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
