### ISSUE TITLE
GifImage显示动画缓慢

### ISSUE THREAD

**Issue by liesauer** [NaBian/HandyControl#1140]
有点像微信里发大动图一样，会以一个很慢的速度播放（大概0.5x这样子），小动图不会，大点的动图就会这样，比如下面这张

![image](https://s2.ax1x.com/2019/10/02/uw99UJ.gif)

**Comment by liesauer** [comment]
这是控件的播放速度
![GIF 2022-3-17 15-08-32](https://user-images.githubusercontent.com/8676741/158755412-9204cbf8-5f02-4d47-acc5-4f129ee9a84f.gif)

**Comment by NaBian** [comment]
hc 的 gif 控件抽取自 winform，暂不支持更为精细的操控，比如帧率控制，可使用专门的 gif 库。
