### ISSUE TITLE
[Feature request] Add mouse option clicking in hc:StepBar

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1142]
**Is your feature request related to a problem? Please describe.**

In our application we use a `<hc:StepBar>` for showing a 3 step process for the cashier to close the cash register at the end of the day, as shown in the image:

![image](https://user-images.githubusercontent.com/7988351/159745521-20ed44bc-4d32-4793-b6a4-1e87b62626d9.png)

When testing our application in a closed beta against real users, one of our test users atempted to click the `StepBar` labels instead of clicking the `Previous` (Atrás) and `Next` (Siguiente) buttons at the bottom of the form. We realized that it would be nice if we can somehow change the current step when the user clicks on the step label or icon.

Our current setup looks like this:

```xaml
<hc:StepBar VerticalAlignment="Top" Dock="Left" StepIndex="{Binding StepIndex}" ItemsSource="{Binding StepsList}" Height="Auto">
    <hc:StepBar.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding Title}"/>
        </DataTemplate>
    </hc:StepBar.ItemTemplate>
</hc:StepBar>
```

**Describe the solution you'd like**

It could be great if the StepBar automatically updates the ViewModel "StepIndex" when the user clicks the step icon or label.
Some HandyControl users may not want this behaviour, so an option called `CanBeSelectedWithMouse="False"` could be added.

**Describe alternatives you've considered**
I've tried to add a custom `MouseUp` event handler to the textBlock but I don't think it fits nice.

**Additional context**
-

**Comment by Yopler** [comment]
Hi 🖐,

I think this feature can be nice. As an alternative, you can add a `Button `with a custom style instead of the `TextBlock`.

**Comment by jhm-ciberman** [comment]
Yes, I was writing the example on the fly and forgot to add the ´<Button>´ element. Edited the post for clarity

**Comment by jhm-ciberman** [comment]
Yes, true. The problem is that you cannot click on the number icon on the left.
