### ISSUE TITLE
如何设置TimePicker的默认时间

### ISSUE THREAD

**Issue by easyboot** [NaBian/HandyControl#1151]
### Describe the bug

我想设置TimePicker的默认时间为 00:00:00.但是我总是得到的是当前时间。
我改如何设置呢
![image](https://user-images.githubusercontent.com/26960023/161776237-c6bc5b3a-cb04-4345-92a0-43338272520e.png)

![image](https://user-images.githubusercontent.com/26960023/161776368-e468ab31-e476-4103-b67c-af94e4ba13fb.png)

### Steps to reproduce the bug

我该如何设置呢

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2019

### Framework type

.Net Core 3.1

### Windows version

May 2021 Update (19043)

**Comment by NaBian** [comment]
SelectedTime
