### ISSUE TITLE
NotifyIcon在Explorer重启后消失

### ISSUE THREAD

**Issue by ZhouShuren1881** [NaBian/HandyControl#1169]
## 问题描述
如题，windows资源管理器崩溃是一个常见问题。HC的Notifyicon类在任务栏重启后不会自动恢复，但Visibility等属性一直为可见，即使资源管理器崩溃后重新设置Visibility属性，图标也不会出现。
## 原生NotifyIcon没有这个问题
由于WPF没有提供原生托盘图标，可供参考的只有WinForm的notifyicon，经测试，WinForm的托盘图标在资源管理器崩溃后仍然可见。

### Steps to reproduce the bug

1. 新建一个HC工程
2. 任意添加在一个HandyControl.Controls.NotifyIcon并显示在托盘中
3. 打开我的电脑
4. 打开任务管理器，重启Explorer

您会看到：托盘中的图标消失，程序缺没有提示任何异常。

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by xianyunleo** [comment]
同样的问题，很久了

**Comment by lanzhiquan** [comment]
> 同样的问题，很久了

这个库很久都没人管了，有BUG自己修将就下吧。

**Comment by ZhouShuren1881** [comment]
> 

3月不是还有很多commit嘛，就是issues没人管... 现在被迫用winform实现托盘菜单

**Comment by ZhouShuren1881** [comment]
> > 同样的问题，很久了
> 
> 这个库很久都没人管了，有BUG自己修将就下吧。

我看一直有活跃的Commit啊，怎么issues就没人管呢

**Comment by lanzhiquan** [comment]
> > > 同样的问题，很久了
> > 
> > 
> > 这个库很久都没人管了，有BUG自己修将就下吧。
> 
> 我看一直有活跃的Commit啊，怎么issues就没人管呢

那也要看看commit的是啥了，开源就这样，上一个有效commit是在4月1日，最后修一个bug是3月28，这样的进度，一年也只能修十几二十个BUG。feature就更不用说了，自己加个feature还不一定被merge，这就是搞心态呀，哈哈。

**Comment by xianyunleo** [comment]
@lanzhiquan @ZhouShuren1881  https://github.com/lepoco/wpfui 刚发现了这个项目不错

**Comment by NaBian** [comment]
实在太忙了，各位大佬见谅！ 😢

**Comment by GF-Huang** [comment]
> @lanzhiquan @ZhouShuren1881 [lepoco/wpfui](https://github.com/lepoco/wpfui) 刚发现了这个项目不错

换库 约等于 换 BUG。🙄
