### ISSUE TITLE
[BUG] ListBoxItem IsSelected Shows Incorrect Color on Startup

### ISSUE THREAD

**Issue by nlogozzo** [NaBian/HandyControl#1178]
### Describe the bug

Creating a `ListBox` with `Style="{StaticResource ListBoxModernStyle}"` and adding a few `ListBoxItems` and setting `IsSelected="True"` on one item produces this result when you first run the application:
![image](https://user-images.githubusercontent.com/17648453/166694816-32130a5f-da4c-4713-a7e5-69cf6538c663.png)
The item is selected, but the color shown is the one shown when the window is deactivated, not the proper accent color.

### Steps to reproduce the bug

```xml
        <ListBox HorizontalAlignment="Left" VerticalAlignment="Stretch" Width="200" BorderThickness="0" Background="Transparent" Style="{StaticResource ListBoxModernStyle}">
            <ListBoxItem IsSelected="True">
                <ListBoxItem.Content>
                    <StackPanel Orientation="Horizontal">
                        <TextBlock FontFamily="Segoe Fluent Icons" FontSize="18" Text="&#xe80f;"/>

                        <TextBlock Margin="8,0,0,0" Text="Home"/>
                    </StackPanel>
                </ListBoxItem.Content>
            </ListBoxItem>

            <ListBoxItem>
                <ListBoxItem.Content>
                    <StackPanel Orientation="Horizontal">
                        <TextBlock FontFamily="Segoe Fluent Icons" FontSize="18" Text="&#xe7c3;"/>

                        <TextBlock Margin="8,0,0,0" Text="Form"/>
                    </StackPanel>
                </ListBoxItem.Content>
            </ListBoxItem>

            <ListBoxItem>
                <ListBoxItem.Content>
                    <StackPanel Orientation="Horizontal">
                        <TextBlock FontFamily="Segoe Fluent Icons" FontSize="18" Text="&#xe713;"/>

                        <TextBlock Margin="8,0,0,0" Text="Settings"/>
                    </StackPanel>
                </ListBoxItem.Content>
            </ListBoxItem>
        </ListBox>
```

### Expected behavior

The item is selected with the proper accent color:
![image](https://user-images.githubusercontent.com/17648453/166695215-4ac6a947-1b1c-4cce-bb4e-b7cb01ff772a.png)

### NuGet package version

HandyControls (Custom version) 3.3.11

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Insider Build (xxxxx)

**Comment by Yopler** [comment]
Hi @nlogozzo🖐,

This is not a bug, this the default behavior based on the behavior of the default style of wpf. 

`ListBoxItem` have 2 state when selected : they can be focus or not. When you start your application, nothing is focus.
You can see in the source code : 

[ModernListBoxBaseStyles.xaml#L82](https://github.com/ghost1372/HandyControls/blob/d34a5031882df3df696bb8fdf639b0df3d029857/src/Shared/HandyControl_Shared/Themes/Styles/Base/HandyControls/ModernListBoxBaseStyles.xaml#L82)
```xaml
<!--Selected and focus style-->
            <Trigger Property="IsSelected" Value="true">
                <Setter Property="Background" Value="{DynamicResource PrimaryBrush}"/>
                <Setter Property="Foreground" Value="{DynamicResource TextIconBrush}"/>
            </Trigger>

<!--Selected and not focus style-->
            <MultiTrigger>
                <MultiTrigger.Conditions>
                    <Condition Property="IsSelected" Value="true"/>
                    <Condition Property="Selector.IsSelectionActive" Value="false"/>
                </MultiTrigger.Conditions>
                <Setter Property="Background" Value="{DynamicResource DarkDefaultBrush}"/>
                <Setter Property="Foreground" Value="{DynamicResource PrimaryTextBrush}"/>
            </MultiTrigger>
```

If you want to modify this behavior, there is multiple solution : 
- the cleanest one : create your `ListBoxItem` style based on `ListBoxModernItemBaseStyle` and overwrite this behavior.

**App.xaml**
```xaml
<Style x:Key="MyStyle" TragetType="ListBoxItem" BasedOn="ListBoxModernItemBaseStyle">
        <Style.Triggers>
            <MultiTrigger>
                <MultiTrigger.Conditions>
                    <Condition Property="IsSelected" Value="true"/>
                    <Condition Property="Selector.IsSelectionActive" Value="false"/>
                </MultiTrigger.Conditions>

<!--your behavior-->

            </MultiTrigger>
        </Style.Triggers>
</Style>
```

- the easiest one : overwrite the `DarkDefaultBrush` and `PrimaryTextBrush` by the Selected and focus color in your `ListBox` ressources. Be careful doing this, the overwrite of the color apply on every children of your `ListBox` so you can sometimes have a surprising color behvior. 

```xaml
        <ListBox HorizontalAlignment="Left" VerticalAlignment="Stretch" Width="200" BorderThickness="0" Background="Transparent" Style="{StaticResource ListBoxModernStyle}">
            <ListBox.Resources>
                  <SolidColorBrush x:Key="DarkDefaultBrush" Color="YourColor"/>
                  <SolidColorBrush x:Key="PrimaryTextBrush" Color="YourColor"/>
            </ListBox.Resources>
<!--....-->

        </ListBox>
```


hope it can help 😊

PS : However this issue, is very specific to the fork from HandyControls of @ghost1372 . I think it is on his repo, that you should put this issue

**Comment by nlogozzo** [comment]
> PS : However this issue, is very specific to the fork from HandyControls of @ghost1372 . I think it is on his repo, that you should put this issue

Thank you :) I opened the issue there
