### ISSUE TITLE
datagrid:the columnheaders were disappeared

### ISSUE THREAD

**Issue by chrismx000** [NaBian/HandyControl#1180]
datagrid with emtry itemssource and setting <DataGridTextColumn Width="*",Header="xxxx"> , the columnheaders were disappeared,why??

**Comment by Chadwuo** [comment]
Man, have you found the reason

**Comment by chrismx000** [comment]
今天刚找到原因。这个版本代码作者是想你空的时候，显示无数据，就不显示表头。
问题出在这，
   <hc:ToggleBlock IsChecked="{Binding HasItems,RelativeSource={RelativeSource AncestorType=DataGrid},Mode=OneWay}" Grid.ColumnSpan="3" Grid.Column="0" Grid.Row="1" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch">
                                            <hc:ToggleBlock.CheckedContent>
                                                <ScrollContentPresenter x:Name="PART_ScrollContentPresenter" CanContentScroll="{TemplateBinding CanContentScroll}"/>
                                            </hc:ToggleBlock.CheckedContent>
                                            <hc:ToggleBlock.UnCheckedContent>
                                                <hc:Empty />
                                            </hc:ToggleBlock.UnCheckedContent>
                                        </hc:ToggleBlock>
没数据直接不显示了。解决方法就是将里面ScrollContentPresenter放外面就完事。
显示那个无数据的图，可以在datagrid那设置hc:Emtry.ShowEmpty="true"。
