### ISSUE TITLE
[Feature request] LoadingRing

### ISSUE THREAD

**Issue by nlogozzo** [NaBian/HandyControl#1181]
We have a `LoadingCircle` but could we also see a `LoadingRing` similar to the new Windows 11 style progress ring.
![image](https://user-images.githubusercontent.com/17648453/167260144-208c4d5d-8caa-4b9b-908f-92465b285b1c.png)
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.progressring?view=winui-3.0

**Comment by NaBian** [comment]
you can try CircleProgressBar

**Comment by nlogozzo** [comment]
Oh, didn't see that there! Perfect, thank you!
