### ISSUE TITLE
窗体最大化时启动growl全局通知会卡死

### ISSUE THREAD

**Issue by SaledCabbage** [NaBian/HandyControl#1182]
### Describe the bug

将窗体设置为最大化时调用Global.ErrorGlobal()等带有Global的方法会出错

### Steps to reproduce the bug

1、将窗体设置最大化
2、发送Growl信息通知

**Comment by mopocv** [comment]
https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-820859410

**Comment by NaBian** [comment]
as above
