### ISSUE TITLE
WPF窗体最大化，鼠标移动到消息框会报错

### ISSUE THREAD

**Issue by easyboot** [NaBian/HandyControl#1186]
### Describe the bug

HandyControl.Controls.Growl.SuccessGlobal(msg1);
我使用Growl，如果窗体最大化，则鼠标不能移动到消息框内。否则会报错如下图
![image](https://user-images.githubusercontent.com/26960023/168951228-f7f6cbd0-3df8-49a7-bec6-3bcba7e8554d.png)

### Steps to reproduce the bug

窗体最大化运行后，消息报错

**Comment by 342241794** [comment]
我用的3.4版本,使用 "HandyControl.Controls.Growl.InfoGlobal("message")"也是遇到了相同的问题.有解决方案么?不用Global正常.

**Comment by lingopen** [comment]
https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-820859410  这里已经解决了
