### ISSUE TITLE
ConfigHelper.Instance.SetLang 无效

### ISSUE THREAD

**Issue by Paodange** [NaBian/HandyControl#1196]
### Describe the bug

3.3.0版本通过ConfigHelper.Instance.SetLang后 MessageBox上的按钮文字不会切换成对应的语言，始终显示为中文。

### Steps to reproduce the bug

```csharp
HandyControl.Tools.ConfigHelper.Instance.SetLang("en");   //设置语言为英语
HandyControl.Controls.MessageBox.Show("aaa","title",MessageBoxButton.YesNo)   // MessageBox上面的两个按钮始终显示为 是和否 未跟随语言切换
```

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

**Comment by Paodange** [comment]
安装对应的语言包后解决  谢谢

**Comment by Paodange** [comment]
安装对应的语言包后解决

**Comment by Farb** [comment]
好吧，遇到同样的问题了
