### ISSUE TITLE
NumericUpDown的Title用绑定无效

### ISSUE THREAD

**Issue by nnn149** [NaBian/HandyControl#1203]
### Describe the bug

我在使用`hc:InfoElement.Title="{Binding Key,Mode=OneWay}"
`绑定到Key，一个String类型，界面上不会显示Titile，
但是用`hc:TextBox`绑定title是可以显示的。
调整`hc:InfoElement.TitlePlacement="Left"`也不会显示。

### Steps to reproduce the bug

```c#
<ListBox Style="{StaticResource ListBoxWrapStyle}"
            ItemsSource="{Binding AimTypes}"
                ItemContainerStyle="{StaticResource ItemContainerStyle1}" 
                ScrollViewer.HorizontalScrollBarVisibility="Disabled" SelectionMode="Single">
    <ListBox.ItemTemplate>
        <DataTemplate>
            <DockPanel>
                <TextBlock HorizontalAlignment="Center"  Text="{Binding Key,Mode=OneWay}" Style="{StaticResource TextBlockDefault}"/>
                <hc:NumericUpDown hc:InfoElement.Title="{Binding Key,Mode=OneWay}"  DecimalPlaces="2" Value="{Binding Value}" Increment="0.01" Maximum="2" Minimum="0.01"/>
            </DockPanel>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

### Expected behavior

绑定后title正常显示。

### Screenshots

![image](https://user-images.githubusercontent.com/23712868/173755871-134c3957-c526-499b-8e19-3bbb0344734a.png)

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
使用 NumericUpDownExtend 样式
