### ISSUE TITLE
TabControl TabItem问题

### ISSUE THREAD

**Issue by 424358225** [NaBian/HandyControl#1205]
之前有人提出用鼠标中键关闭标签页，但是TabItem是3D视图的话，在content 按下中键 ，本来是希望视图旋转的，但是造成了关闭标签，希望开放Midbutton的选项

**Comment by NaBian** [comment]
具体如何开放可以详细说明下吗？

**Comment by 424358225** [comment]
> 具体如何开放可以详细说明下吗？

例如设置一个MidBtnCloseVisible {BOOL}属性，
我可以选择按下滚轮键是否启用
