### ISSUE TITLE
如何更改hc:ScrollViewer滚动条的颜色？

### ISSUE THREAD

**Issue by li-zheng-hao** [NaBian/HandyControl#1209]
![image](https://user-images.githubusercontent.com/22129824/177955292-ecd18cdd-c176-4f06-84fb-f526689079b0.png)

在源码中看到是在`ScrollBarBaseStyle`中设置的滚动条颜色，请问如果我要修改为自己定义的颜色，最简单的方法是什么？

目前我能想到的方法就是把ScrollViewer的整个样式从源码中复制到自己的工程再修改一下，但是这样做感觉效率有点低

**Comment by jinleil** [comment]
你好 这个问题解决了吗 我也遇到相同的问题

**Comment by li-zheng-hao** [comment]
> 你好 这个问题解决了吗 我也遇到相同的问题

如果只想改颜色的话，最简单的办法就是在自己的样式文件中定义`primaryTextbrush`，如果要定制样式，需要继承该样式表然后修改

**Comment by jinleil** [comment]
我只是想把控件库中的主色调PrimaryColor 改成我自己想要的颜色
![image](https://user-images.githubusercontent.com/44106819/178884499-4619ac98-33eb-4400-b29e-635229d526ab.png)

**Comment by jinleil** [comment]
![1657767033255](https://user-images.githubusercontent.com/44106819/178887672-753687e7-5b51-43d7-97f7-7a8dc40b373e.png)
程序启动时可以通过代码的方式把资源中的颜色改掉

**Comment by li-zheng-hao** [comment]
> ![1657767033255](https://user-images.githubusercontent.com/44106819/178887672-753687e7-5b51-43d7-97f7-7a8dc40b373e.png) 程序启动时可以通过代码的方式把资源中的颜色改掉

不用这么复杂....你直接在样式文件改就好了呀

**Comment by jinleil** [comment]
![1657768064624](https://user-images.githubusercontent.com/44106819/178889551-5db3f6fd-87b6-45f9-a204-ead7bc0b6cdd.png)

**Comment by NaBian** [comment]
``` xml
<ScrollViewer>
    <ScrollViewer.Resources>
        <SolidColorBrush x:Key="PrimaryTextBrush" Color="Red"/>
        <SolidColorBrush x:Key="SecondaryTextBrush" Color="Blue" />
    </ScrollViewer.Resources>
</ScrollViewer>
```
