### ISSUE TITLE
ToolBar not rounded

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1223]
### Describe the bug

My ToolBar:
![Snipaste_2022-07-26_18-18-45](https://user-images.githubusercontent.com/7220248/180983315-5f5d6036-1d4f-434c-ba7d-e375c97f8cf0.png)

Demo ToolBar:
![Snipaste_2022-07-26_18-18-18](https://user-images.githubusercontent.com/7220248/180983327-67a72579-9482-4533-9bad-fc58ed70863a.png)

### Steps to reproduce the bug

Create a simple ToolBar.

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by Yopler** [comment]
Hi 🖐,

Did you override the `DefaultCornerRadius `property ?
You can try to use the `hc:BorderElement.CornerRadius` property in your toolbar.

Hope it can help 😊

**Comment by CodingOctocat** [comment]
@Yopler `hc:BorderElement.CornerRadius` not work.

I use `Border` wrapper to solve this issue:
```XAML
<Border CornerRadius="4"
        Style="{StaticResource BorderClip}">
    <ToolBarTray />
</Border/
```

**Comment by CodingOctocat** [comment]
@Yopler I create a blank WPF app, Toolbar with rounded corners, I can't find what's wrong, no override.

**Comment by CodingOctocat** [comment]
@Yopler I found the reason, `ToolBarTray` does not support rounded corners, `ToolBar` is rounded corners, but I set the `ToolBarTray` background to gray for the toolbar row horizontal stretch, `ToolBar` background set to transparent, so you can not see the rounded corners.
