### ISSUE TITLE
hc:TextBox无法正常输入小数

### ISSUE THREAD

**Issue by w-s-q** [NaBian/HandyControl#1226]
### Describe the bug

当hc:TextBox的text绑定的数据类型为float或者double类型时，无法正常的输入小数点。比如当输入12.3时，只能先输入123,然后鼠标移到2和3之间，输入小数点。

### Steps to reproduce the bug

1、在ViewModel中有一个Point属性，类型是float
2、在View上添加一个hc:Text控件，Value绑定 Value="{Binding Point, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"
3、启动程序，输入小数。

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

**Comment by NaBian** [comment]
该行为和原生一致，可以删除 ```UpdateSourceTrigger=PropertyChanged```，采用后置验证。
