### ISSUE TITLE
SplitButton can not raise Command

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1228]
### Describe the bug

I create a `SplitButton`, At first I used `Click` event, but clicking on the dropdown button also triggers `Click` event, which is not what I want.

Then I used `Command`, but it never triggered the command. I tried HandyControl's `SimpleRelayCommand`, `AsyncComand` etc. but to no avail!

### Steps to reproduce the bug

1. Create a `SplitButton`
2. Add Command(SimpleRelayCommand)

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by CodingOctocat** [comment]
Share a temporary solution to this issue:

```CS
private void MySplitButton_Click(object sender, RoutedEventArgs e)
{
    if (MySplitButton.IsDropDownOpen)
    {
        return;
    }

   // Do something.
}
```

**Comment by NaBian** [comment]
can not reproduce, pls provide demo.

**Comment by CodingOctocat** [comment]
I created a new simple example, but I can't reproduce the problem either, and since my problem project has changed, I can't restore it for now, and this issue is closed for now.
