### ISSUE TITLE
在类型为Drawer的对象上找不到xxx属性

### ISSUE THREAD

**Issue by huangjingli** [NaBian/HandyControl#1231]
1.使用场景：点击按钮时打开一个Drawer，Drawer里面有TextBox 控件作为用户输入的内容，并通过动态属性绑定的方式把值传入后台。
2.提示报错信息：
![image](https://user-images.githubusercontent.com/38234023/182152802-c352194a-3500-41b6-99d6-45dfffba0a72.png)
3.但使用的显示页面传值是正常的，调试就是显示以上报错信息，请问是什么原因，是不能是Drawer里面动态绑定事件或者属性吗？

**Comment by NaBian** [comment]
请提供 demo。

**Comment by wudilianggg** [comment]
Binding  Source={x:Reference Name}}
控件域不通 不能常规绑定

**Comment by heraclesly** [comment]
你好，你这个问题解决了吗

**Comment by wudilianggg** [comment]
是的 绑定的语法改一下 改成Binding Source={x:Reference Name},Path}&nbsp;
参考资料：https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/wpf-xaml-namescopes?redirectedfrom=MSDN&amp;view=netframeworkdesktop-4.8
https://blog.csdn.net/qq_34511664/article/details/108984018




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午4:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HandyOrg/HandyControl] 在类型为Drawer的对象上找不到xxx属性 (Issue #1231)





 
你好，你这个问题解决了吗

**Comment by heraclesly** [comment]
我的是绑定的Command

**Comment by wudilianggg** [comment]
command一直可以用啊&nbsp; 他这个问题是绑定控件属性失效&nbsp; 包括drawe容器内控件相互绑定也会失效




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HandyOrg/HandyControl] 在类型为Drawer的对象上找不到xxx属性 (Issue #1231)





 
我的是绑定的Command

**Comment by wudilianggg** [comment]
这是drawer 他所描述的问题demo 里面有一个是能绑定的代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HandyOrg/HandyControl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HandyOrg/HandyControl] 在类型为Drawer的对象上找不到xxx属性 (Issue #1231)





 
我的是绑定的Command

**Comment by heraclesly** [comment]
命令是可以用，也会触发，但是会有个找不到command的错误，不影响实际使用，只是看的不舒服
![image](https://user-images.githubusercontent.com/39791352/191921983-2937ef89-c5b3-447b-aa3d-eaec70daef63.png)

**Comment by qwfy168** [comment]
> 命令是可以用，也会触发，但是会有个找不到command的错误，不影响实际使用，只是看的不舒服 ![image](https://user-images.githubusercontent.com/39791352/191921983-2937ef89-c5b3-447b-aa3d-eaec70daef63.png)

你这个问题解决了吗，我也是存在相同情况

**Comment by heraclesly** [comment]
> > 命令是可以用，也会触发，但是会有个找不到command的错误，不影响实际使用，只是看的不舒服 ![image](https://user-images.githubusercontent.com/39791352/191921983-2937ef89-c5b3-447b-aa3d-eaec70daef63.png)
> 
> 你这个问题解决了吗，我也是存在相同情况

没，老板叫我做别的去了，暂时没处理这个。你找到问题可以踢我一下吗

**Comment by NaBian** [comment]
Drawer 使用的是装饰器控件，xaml 设计器支持不友好。
