### ISSUE TITLE
[Feature request]请问有无做知识图谱控件的计划？

### ISSUE THREAD

**Issue by asasn** [NaBian/HandyControl#1232]
如果能有一个面板布局，把知识图谱的点边关系可视化就好了
如果能够点击实体按钮，或者关系线，进入到编辑状态，那就更好了……
![image](https://user-images.githubusercontent.com/48091517/182759057-2d1ebf55-c32c-4b08-8c0f-80450babddc0.png)
其实这类东西，是有一些现成的软件，但需要额外安装第三方软件比较麻烦，不好集成在自己的wpf软件里面

**Comment by NaBian** [comment]
没有这方面计划
