### ISSUE TITLE
[BUG] HandyControls v3.4.1 breaks the themes

### ISSUE THREAD

**Issue by jhm-ciberman** [NaBian/HandyControl#1236]
### Describe the bug

Hello. I upgraded from HandyControls **v3.3.11** to **v3.4.1** and the application theme breaks. (The forked version, but I don't know where to put the issue). 

- The theme does not fully changes when the `ThemeManager.Current.ApplicationTheme` property changes. It changes partially, leaving the UI in an inconsistent state. 
- Colors from each theme are the default ones provided by HandyControls and the overwritten values are not respected.

## Configuration

**In my App.xaml**

```xaml
<hc:ThemeResources UsingSystemTheme="False" RequestedTheme="Light">
    <hc:ThemeResources.ThemeDictionaries>
        <ResourceDictionary x:Key="Light" hc:ThemeDictionary.Key="Light" Source="/Dictionaries/ThemeLight.xaml"/>
        <ResourceDictionary x:Key="Dark" hc:ThemeDictionary.Key="Dark" Source="/Dictionaries/ThemeDark.xaml"/>
    </hc:ThemeResources.ThemeDictionaries>
</hc:ThemeResources>
```

**In my Code behind to change the theme:**
```csharp
using HandyControl.Themes;

public void UpdateTheme(RegisCarTheme theme)
{
    _ = this.Dispatcher.BeginInvoke(() =>
    {
        switch (theme)
        {
            case RegisCarTheme.Automatic:
                ThemeManager.Current.ApplicationTheme = ThemeManager.GetSystemTheme();
                break;
            case RegisCarTheme.Light:
                ThemeManager.Current.ApplicationTheme = ApplicationTheme.Light;
                break;
            case RegisCarTheme.Dark:
                ThemeManager.Current.ApplicationTheme = ApplicationTheme.Dark;
                break;
        }
    });
}
```

**In my overridden themes: "/Dictionaries/ThemeDark.xaml"**

```xaml
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:hc="https://handyorg.github.io/handycontrol">

    <SolidColorBrush x:Key="BackgroundBrush" Color="#27272a" />
    <!-- More colors overridden here. Omitted for brevity. -->

</ResourceDictionary>
```

### Steps to reproduce the bug

1. Upgrade from HandyControls **v3.3.11** to **v3.4.1**.
2. Create a setup similar to the described above. (Two buttons, that change the UI theme)
3. The theme will not be fully swapped leaving some colors from the old theme.
4. If any color is overwritten in custom Resource Dictionaries, they are not used. 

### Expected behavior

The theme should change acordingly. See below for screenshots. 

## In v3.3.11 (Correct behavior)
- The theme changes automatically whenever the `ThemeManager.Current.ApplicationTheme` property changes.
- Colors from each theme are used from the overwritten values (see the "App.xaml" code). 

| Condition | Light theme | Dark Theme
-------------|---------------|------------------
| Always. This is the expected behavior | ![image](https://user-images.githubusercontent.com/7988351/184755864-c7882767-6390-49c9-9e0c-6f2354dd6462.png)  | ![image](https://user-images.githubusercontent.com/7988351/184756081-96e0697a-febe-4aec-8339-06048c1f78e5.png)

## In v3.4.1 (Incorrect behavior)

- The theme does not fully changes when the `ThemeManager.Current.ApplicationTheme` property changes. It changes partially, leaving the UI in an inconsistent state. 
- Colors from each theme are the default ones provided by HandyControls and the overwritten values are not respected.

| Condition | Light theme | Dark Theme
|------------|---------------|------------------
| When `RequestedTheme="Light"` in `App.xaml` | ![image](https://user-images.githubusercontent.com/7988351/184757286-77af5c64-413a-4f35-9fd9-4ef995a5c686.png) | ![image](https://user-images.githubusercontent.com/7988351/184757310-4376fc3c-c63e-4351-95b7-18d9f2a2505a.png)
| When `RequestedTheme="Dark"` in `App.xaml` | ![image](https://user-images.githubusercontent.com/7988351/184756764-6de36861-cb96-4e9e-a4f0-4858934794e5.png) | ![image](https://user-images.githubusercontent.com/7988351/184756746-93434c3b-bb7d-4c37-9d5e-d337a7172727.png)

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

May 2021 Update (19043)

### Additional context

Related issue in forked HandyControls repo: https://github.com/ghost1372/HandyControls/issues/158

**Comment by NaBian** [comment]
We haven't released 3.4 yet.
