### ISSUE TITLE
ResourceHelper.GetTheme("HandyTheme", Resources).Skin = skin;  - No GetTheme() with 2 arguments

### ISSUE THREAD

**Issue by Andrey-2021** [NaBian/HandyControl#1249]
### Describe the bug

Hi!

In 
[https://ghost1372.github.io/handycontrol/theme/handyControl](your examle)

`internal void UpdateSkin(SkinType skin)
{
    SharedResourceDictionary.SharedDictionaries.Clear();
    ResourceHelper.GetTheme("HandyTheme", Resources).Skin = skin;
    Current.MainWindow?.OnApplyTemplate();
}`

But there is NO 
GetTheme() witn two arguments,
When press F12, we can see onli

` public static ResourceDictionary GetTheme()
        {
            return _theme ?? (_theme = GetStandaloneTheme());
        }
`

### Steps to reproduce the bug

1. Repite example 
[https://ghost1372.github.io/handycontrol/theme/handyControl](exaple)

`internal void UpdateSkin(SkinType skin)
{
    SharedResourceDictionary.SharedDictionaries.Clear();
    ResourceHelper.GetTheme("HandyTheme", Resources).Skin = skin;
    Current.MainWindow?.OnApplyTemplate();
}`

It's not work

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

May 2020 Update (19041)

### Additional context

Thenks

**Comment by K780420** [comment]
> ### Describe the bug
> 
> Hi!
> 
> 
> 
> In 
> 
> [https://ghost1372.github.io/handycontrol/theme/handyControl](your examle)
> 
> 
> 
> `internal void UpdateSkin(SkinType skin)
> 
> {
> 
>     SharedResourceDictionary.SharedDictionaries.Clear();
> 
>     ResourceHelper.GetTheme("HandyTheme", Resources).Skin = skin;
> 
>     Current.MainWindow?.OnApplyTemplate();
> 
> }`
> 
> 
> 
> But there is NO 
> 
> GetTheme() witn two arguments,
> 
> When press F12, we can see onli
> 
> 
> 
> ` public static ResourceDictionary GetTheme()
> 
>         {
> 
>             return _theme ?? (_theme = GetStandaloneTheme());
> 
>         }
> 
> `
> 
> 
> 
> ### Steps to reproduce the bug
> 
> 1. Repite example 
> 
> [https://ghost1372.github.io/handycontrol/theme/handyControl](exaple)
> 
> 
> 
> `internal void UpdateSkin(SkinType skin)
> 
> {
> 
>     SharedResourceDictionary.SharedDictionaries.Clear();
> 
>     ResourceHelper.GetTheme("HandyTheme", Resources).Skin = skin;
> 
>     Current.MainWindow?.OnApplyTemplate();
> 
> }`
> 
> 
> 
> It's not work
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Screenshots
> 
> _No response_
> 
> ### NuGet package version
> 
> _No response_
> 
> ### IDE
> 
> Visual Studio 2022
> 
> ### Framework type
> 
> .Net 6.0
> 
> ### Windows version
> 
> May 2020 Update (19041)
> 
> ### Additional context
> 
> Thenks

**Comment by NaBian** [comment]
we have moved GetTheme method to Theme class.
