### ISSUE TITLE
Links with "%20" cannot be opened correctly

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1250]
### Describe the bug
https://github.com/ghost1372/HandyControls/blob/84757052d3b324b15bdeff829f4d1bc1f0e027fb/src/Shared/HandyControl_Shared/Interactivity/Commands/OpenLinkCommand.cs#L11-L29

In most cases, OpenLinkCommand works fine, but if the link contains "%20", then it does not work as expected.

Test link:
[https://cdn.pixabay.com/vimeo/570048615/Hello%20-%2079584.mp4?width=1920&hash=0d95b702da905bcc9d657f482643c530abc9690d&download=1](https://cdn.pixabay.com/vimeo/570048615/Hello%20-%2079584.mp4?width=1920&hash=0d95b702da905bcc9d657f482643c530abc9690d&download=1)

Solution:
```CS
public static void OpenUri(string uri)
{
    // If not converted to AbsoluteUri, the "%20" in the link will be whitespace and the command line argument will be truncated.
    string absoluteUri = new Uri(uri, UriKind.RelativeOrAbsolute).AbsoluteUri;
    absoluteUri = absoluteUri.Replace("&", "^&");

    var psi = new ProcessStartInfo {
        FileName = "cmd",
        WindowStyle = ProcessWindowStyle.Hidden,
        UseShellExecute = true,
        CreateNoWindow = true,
        Arguments = $"/c start {absoluteUri}"
    };

    Process.Start(psi);
}

```

### Steps to reproduce the bug

1. Create a Button with OpenLinkCommand
2. Pass in the above test link

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
HandyControl 暂未发布 3.4 版本，并且也无法复现该问题。
