### ISSUE TITLE
Maximized Windows gets off monitor

### ISSUE THREAD

**Issue by Enat0** [NaBian/HandyControl#1258]
### Describe the bug

When we have more than 1 monitor screen and we maximize the windows, it gets off the monitor.

If WindowState is set to "Maximized" it works fine, but if you resize and then maximize it gets off the monitor.

### Steps to reproduce the bug

1. <hc:Window x:Class="testes.MainWindow"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:hc="https://handyorg.github.io/handycontrol"
mc:Ignorable="d"
Title="Title"
Height="450"
Width="800" >

</hc:Window>

2.Maximize the screen

### Screenshots

![186716245-2420163f-0654-41f7-875e-e418618276d0](https://user-images.githubusercontent.com/100444259/188672668-5518d59f-9c4b-444b-a41d-daadac53eaa2.png)

(I drew a black line to simulate the two monitors)

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

**Comment by 4hera** [comment]
WindowStyle="None" worked for me
