### ISSUE TITLE
`RangeSlider` does not respect the `Ticks` property for drawing

### ISSUE THREAD

**Issue by GF-Huang** [NaBian/HandyControl#1269]
### Code

```xaml
<hc:RangeSlider VerticalAlignment="Center" 
                IsSnapToTickEnabled="True" Ticks="{Binding Strikes}" TickPlacement="Both"
                hc:TipElement.Visibility="Visible" hc:TipElement.Placement="Bottom"
                Minimum="{Binding MinStrike}" Maximum="{Binding MaxStrike}" 
                ValueStart="{Binding StartStrike}" ValueEnd="{Binding EndStrike}" />
```

### Ticks

![image](https://user-images.githubusercontent.com/4510984/193447644-e1e83807-adc1-459c-898e-92c4538e309a.png)

### Drawing

In fact, there's no value between 400~432 in `Ticks`, but it draws, and I can snap to it.

![cotdaPsR2m](https://user-images.githubusercontent.com/4510984/193447923-0c77b094-3034-4ead-8c03-b16a05589e79.gif)

### Steps to reproduce the bug

1. Create `RangeSlider` as above code.
2. Binding `Ticks` property in VM.
3. Set `Ticks` later.
4. See the `RangeSlider` drawing and slide it.

### Expected behavior

Only draw ticks what I provided.

### NuGet package version

HandyControls (Custom version) 3.4.2

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Win10 21H2 (19044.2006)

**Comment by NaBian** [comment]
it cannot be reproduced, it's better to provide a demo.

**Comment by GF-Huang** [comment]
[RangeSliderDemo.zip](https://github.com/HandyOrg/HandyControl/files/9729163/RangeSliderDemo.zip)

Click `Update Ticks` button to see slider ticks changes.

**Comment by NaBian** [comment]
use ```DoubleCollection``` instead of ```IReadOnlyList```

**Comment by GF-Huang** [comment]
This seems like a trap.

**Comment by NaBian** [comment]
this behavior is same as slider: [Slider.cs](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/Slider.cs,556)
we try to be as consistent as possible with native control.
if native silder accept ```IReadOnlyList```, so this is a bug of HC.

**Comment by GF-Huang** [comment]
You're right, a trap of WPF.
