### ISSUE TITLE
增加示例代码及文档

### ISSUE THREAD

**Issue by LHTXQ** [NaBian/HandyControl#1274]
#
示例程序的代码只是控件的实现代码，如果能提供如何使用控件的代码就好了（直接从示例程序xaml复制出来，参考微软的WinUI 3 Gallery）：
![image](https://user-images.githubusercontent.com/38943319/195971861-3c1176c2-c958-4d5a-a4de-8483c263c8d8.png)

#
看示例程序代码也翻不到各功能实现代码（打开window的xaml全是空白），希望示例程序结构做得对新手友好些。

#
缺少必要的文档，怎么切换软件主题找半天都没找到（其他UI只需通过Theme.Apply(xxx); 就可以切换主题）。

**Comment by NaBian** [comment]
请阅读 readme

**Comment by LHTXQ** [comment]
Readme中链接的中文文档写得也不全面并且似乎很久没更新了。
另外英文Wiki似乎是他人写的，其中切换主题的代码“
internal void UpdateSkin(SkinType skin)
        {
             Resources.MergedDictionaries.Clear();
            Resources.MergedDictionaries.Add(new ResourceDictionary
            {
                Source = new Uri($"pack://application:,,,/HandyControl;component/Themes/Skin{skin.ToString()}.xaml")
            });
            Resources.MergedDictionaries.Add(new ResourceDictionary
            {
                Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
            });
        }
“
会清除所有资源字典，应该考虑到用户有自己的其他资源。

切换主题的方法应该由控件库实现，并且不应操作用户其他的任何资源字典。


发件人: ***@***.***>
发送时间: 2022年10月15日 16:57
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [HandyOrg/HandyControl] 增加示例代码及文档 (Issue #1274)


请阅读 readme

―
