### ISSUE TITLE
The transfer's SelectedItems alway get left list box SelectedItmes

### ISSUE THREAD

**Issue by galaxyhere** [NaBian/HandyControl#1275]
### Describe the bug

the transfer selectedItem not got expcet result.

### Steps to reproduce the bug

1,create a new transfer control, and set the itemsource,
2,in gui select some items to right list box.
3,check the selectedItems for transfer, the expected result is all the items in Right hand list box , but the actrual  only show selected items in left list box

**Comment by NaBian** [comment]
which version？

**Comment by galaxyhere** [comment]
https://github.com/HandyOrg/HandyControl/commit/76d1787b45110640bde5fbaaeb268dd748465f0f

**Comment by NaBian** [comment]
we added TransferredItems prop.

**Comment by L-MAX6** [comment]
> 我们添加了 TransferredItems 道具。

怎么使用？TransferredItems ={Binding list} 无法访问，hc:ListBoxAttach.SelectedItems无效
