### ISSUE TITLE
hc:Window Win11 22H2 black border at top

### ISSUE THREAD

**Issue by GF-Huang** [NaBian/HandyControl#1277]
## hc:Window

![image](https://user-images.githubusercontent.com/4510984/196500817-5820844c-2496-4396-8195-1699cf8109f3.png)

## Window has no this issue

![image](https://user-images.githubusercontent.com/4510984/196501349-02256772-fe9d-45f6-b712-424b180a9a40.png)

### Steps to reproduce the bug

Just change `Window` class to `hc:Window` of default WPF project template.

### Expected behavior

No black border at top.

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Framework type

.Net 5.0

### Windows version

Windows 11 22H2 (22621.67)

**Comment by GF-Huang** [comment]
@NaBian I found that it is caused by:

https://github.com/HandyOrg/HandyControl/blob/465433560f0fe96bf2bc71e93f60b923d21c7bc6/src/Shared/HandyControl_Shared/Controls/Window/Window.cs#L65

It has different appearance on ~Win10~ Win11 21H2 and Win11 22H2.

**Comment by wangyexiang** [comment]
Dear sir, how do you implement the radius corner of the window？

**Comment by GF-Huang** [comment]
> Dear sir, how do you implement the radius corner of the window？

It's Windows 11 built-in effect.

**Comment by GF-Huang** [comment]
@NaBian  Does this issue hard to fix? Or can not be reproduced? Please let me know. I wonder if I'm the only one having this issue.
