### ISSUE TITLE
Menu animations work only on first time

### ISSUE THREAD

**Issue by NotroDev** [NaBian/HandyControl#1278]
### Describe the bug

Hello. It seems that animation in Menu works only on first use.
Example code:
```xml
<Menu
    x:Name="MenuBar"
    Grid.Column="1"
    Margin="0,2.5,0,0"
    hc:MenuAttach.AnimationMode="Top2BottomWithFade"
    hc:MenuAttach.IsEnabledAnimation="True"
    Background="Transparent"
    FontFamily="Open Sans Medium"
    IsMainMenu="True">
    <MenuItem x:Name="File_MenuItem" Header="File">
        <MenuItem
            Header="File" />
</Menu>
```

### Steps to reproduce the bug

1. Create Menu
2. Enable animations
3. Try it

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
This is a bug of unofficial version.
