### ISSUE TITLE
NumericUpDown potential event leak

### ISSUE THREAD

**Issue by thargy** [NaBian/HandyControl#1287]
### Describe the bug

See https://github.com/HandyOrg/HandyControl/issues/1283#issuecomment-1293809739 👍🏻 https://github.com/HandyOrg/HandyControl/blob/c513f5c6f5f2c5a56a403eb1e038c90aa9a7f427/src/Shared/HandyControl_Shared/Controls/Input/NumericUpDown.cs#L46-L72

https://github.com/HandyOrg/HandyControl/commit/8a66f92089efe65cdd586c2be1c0d95f38627b0d added the new `TextBox_LostFocus` event handler and bound it to `textBox` on [line 69](https://github.com/HandyOrg/HandyControl/blob/c513f5c6f5f2c5a56a403eb1e038c90aa9a7f427/src/Shared/HandyControl_Shared/Controls/Input/NumericUpDown.cs#L69).

However, it did not remove the same handler in [lines 49-52](https://github.com/HandyOrg/HandyControl/blob/c513f5c6f5f2c5a56a403eb1e038c90aa9a7f427/src/Shared/HandyControl_Shared/Controls/Input/NumericUpDown.cs#L49-L52).

### Steps to reproduce the bug

This may not be easily discovered, but should be corrected.

### Expected behavior

The new handler should be removed when changing the `textbox` (as per other existing handlers).

e.g.:
```csharp
if (_textBox != null)
{
    _textBox.PreviewKeyDown -= TextBox_PreviewKeyDown;
    _textBox.TextChanged -= TextBox_TextChanged;
    _textBox.LostFocus -= TextBox_LostFocus;
}
```

### Additional context

This is in the current HEAD, but has not been published to a NuGet as yet.

**Comment by JeremyWu917** [comment]
Hi there,
I got this issues right now.

@NaBian When ?
https://github.com/HandyOrg/HandyControl/issues/1283#issuecomment-1292935634

Many thanks ☕
