### ISSUE TITLE
doc error - `NumericUpDown`

### ISSUE THREAD

**Issue by JeremyWu917** [NaBian/HandyControl#1291]
### Describe the bug

doc error - `NumericUpDown`

![image](https://user-images.githubusercontent.com/54832272/198996897-ea5e49ee-8c7c-456d-bd00-e2d9b80eb5a9.png)

### Steps to reproduce the bug

Click [here](https://handyorg.github.io/handycontrol/extend_controls/numericUpDown/) to see.

**Comment by NaBian** [comment]
closed in #1292，thx @JeremyWu917 😄
