### ISSUE TITLE
CheckComBox 数据绑定后不现实

### ISSUE THREAD

**Issue by jerry-2000** [NaBian/HandyControl#1294]
### Describe the bug

xaml:
<hc:CheckComboBox DisplayMemberPath="Name" x:Name="comBox1" ShowClearButton="True" MaxWidth="380" ItemsSource="{Binding DataList}" Style="{StaticResource CheckComboBoxExtend}" hc:InfoElement.Title="title" Margin="0,32,0,0" ShowSelectAllButton="True">
                <hc:CheckComboBox.ItemContainerStyle>
                    <Style TargetType="hc:CheckComboBoxItem" BasedOn="{StaticResource CheckComboBoxItemBaseStyle}">
                        <Setter Property="IsSelected" Value="{Binding IsSelected}" />
                    </Style>
                </hc:CheckComboBox.ItemContainerStyle>
            </hc:CheckComboBox>

VM:
private List<item> dataList;
public List<item> DataList
{
    get { return dataList; }
    set { dataList = value;RaisePropertyChanged(); }
}
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A11", IsSelected = true });
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A111", IsSelected = true });
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A1111", IsSelected = true });
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A11111", IsSelected = true });

如果后台数据全部为选中状态，则前台checkcombox不显示选中的项

### Steps to reproduce the bug

新建xaml页面，绑定VM，使用prism框架

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

**Comment by NaBian** [comment]
最新代码是否有问题？

**Comment by jerry-2000** [comment]
我项目中用的3.3.0，nuget中没有3.4.0的

**Comment by NaBian** [comment]
3.4 对 checkcombobox 做了改进，修复了一些问题，包括当前的 issue，3.4 会在 11 月发布。

**Comment by jerry-2000** [comment]
好的，再追加个问题，checkcombobox中 SelectedValuePath 属性怎么使用？3.4中是否有改进？

**Comment by jerry-2000** [comment]
能否在nuget中加上3.4的预览版本，我测试一下

**Comment by NaBian** [comment]
https://www.myget.org/feed/handycontrol/package/nuget/HandyControl

**Comment by jerry-2000** [comment]
收到，谢谢



***@***.***
 
发件人： NaBian
发送时间： 2022-11-12 14:28
收件人： HandyOrg/HandyControl
抄送： jerry-2000; Author
主题： Re: [HandyOrg/HandyControl] CheckComBox 数据绑定后不现实 (Issue #1294)
https://www.myget.org/feed/handycontrol/package/nuget/HandyControl

**Comment by jerry-2000** [comment]
更新3.4.0-beat6后，后台数据设置全部选中，运行后必须点击一下才显示
![1](https://user-images.githubusercontent.com/70055984/201499182-6dfdd3b6-6015-4cae-9cf7-5f75789ce7e9.png)
![2](https://user-images.githubusercontent.com/70055984/201499187-1a4ce98c-273d-44a3-99f6-b083ab0bbdbb.png)

**Comment by jerry-2000** [comment]
经验证，更新3.4.0版本后，CheckComBox选项不管是全选还是选择其中几项，都要在前台点一下才会显示，而3.3.0则是：全选情况下，前台点一下显示正常，只选择几项，则显示正常

**Comment by jerry-2000** [comment]
经验证，更新3.4.0版本后，CheckComBox选项不管是全选还是选择其中几项，都要在前台点一下才会显示，而3.3.0则是：全选情况下，前台点一下显示正常，只选择几项，则显示正常

**Comment by JiajunDou** [comment]
3.4.0-beta.36 依然没有修复这个问题
