### ISSUE TITLE
NumericUpDown coercion discrepancy between minimum and maximum limits

### ISSUE THREAD

**Issue by rampaa** [NaBian/HandyControl#1303]
### Describe the bug

NumericUpDown handles minimum and maximum coercion differently

### Steps to reproduce the bug

1. Create a NumericUpDown control that has its minimum limit set to 1 and maximum limit set to 100.
2. Remove the value within the control, type -200 and click to some other control to make the NumericUpDown lose focus. Notice how NumericUpDown coerces -200 into 1 (i.e. the minimum limit of the control)
3. Remove the value within the control, type 200 and click to some other control to make the NumericUpDown lose focus. Notice how NumericUpDown coerces 200 into 20 instead of 100 (i.e. the maximum limit of the control)

### Expected behavior

NumericUpDown shouldn't handle minimum and maximum coercion differently. Preferably maximum limit coercion should act like minimum limit coercion (e.g. 200 should be coerced into 100 not 20, when the maximum limit of the control is set to 100)

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

May 2021 Update (19043)

**Comment by NaBian** [comment]
this issue has been fixed in latest code.

**Comment by NaBian** [comment]
this issue has been fixed in latest code.
