### ISSUE TITLE
3.4版本hc:TextBox的VerifyFunc验证委托失效，ShowClearButton属性失效

### ISSUE THREAD

**Issue by yzcbear** [NaBian/HandyControl#1306]
### Describe the bug

3.4版本hc:TextBox的VerifyFunc验证委托失效，ShowClearButton属性失效

### Steps to reproduce the bug

3.4版本hc:TextBox的VerifyFunc验证委托失效，ShowClearButton属性失效

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

**Comment by zixing131** [comment]
IsError同样不工作了，hc:TextBox似乎没有继承IDataInput接口

**Comment by NaBian** [comment]
3.4 已使用 ```Binding.ValidationRules``` 取代了 ```VerifyFunc```，用法详见 demo。

**Comment by Libra321** [comment]
> 3.4 已使用 `Binding.ValidationRules` 取代了 `VerifyFunc`，用法详见 demo。

没有看到有这个demo呀
