### ISSUE TITLE
PropertyGrid嵌入ScrollView后无法滚动

### ISSUE THREAD

**Issue by Anestis271** [NaBian/HandyControl#1314]
### Describe the bug

我在试着用这种方式为PropertyGrid添加滚动，但是不能奏效
```
<ScrollViewer VerticalScrollBarVisibility="Auto">
    <hc:PropertyGrid SelectedObject="{Binding PropertyModel}" />
</ScrollViewer>
```
添加滚动后，当鼠标位于PropertyGrid中时，无法滚动，但是可以在鼠标位于PropertyGrid边缘时正常滚动或者拖动滚动条来实现滚动。
我浏览了源码，但是没有找到有关焦点或者滚动的有关属性的设置，所以这是因为什么导致的，我可以自行修复吗？

### Steps to reproduce the bug

在一个Height固定的布局中添加如下代码
```
<ScrollViewer VerticalScrollBarVisibility="Auto">
    <hc:PropertyGrid SelectedObject="{Binding PropertyModel}" />
</ScrollViewer>
```
当PropertyGrid的长度超出Height时，理论上来讲应该显示滚动条且可以通过鼠标滚动滚动，但事实上会发生像我在Describe中描述的那样的情况。

### Expected behavior

正常滚动

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Core 3.1

### Windows version

May 2021 Update (19043)

**Comment by Anestis271** [comment]
救救孩子

**Comment by serverlet** [comment]
HandyControl 3.3.0 版本下增加这个附加属性就可以了 hc:ScrollViewer.IsInertiaEnabled="True"

**Comment by Anestis271** [comment]
谢谢您的回复，问题已经解决了，十分感谢
