### ISSUE TITLE
CheckComBox 数据绑定后不显示

### ISSUE THREAD

**Issue by jerry-2000** [NaBian/HandyControl#1318]
### Describe the bug

xaml:
<hc:CheckComboBox DisplayMemberPath="Name" x:Name="comBox1" ShowClearButton="True" MaxWidth="380" ItemsSource="{Binding DataList}" Style="{StaticResource CheckComboBoxExtend}" hc:InfoElement.Title="title" Margin="0,32,0,0" ShowSelectAllButton="True">
hc:CheckComboBox.ItemContainerStyle
<Style TargetType="hc:CheckComboBoxItem" BasedOn="{StaticResource CheckComboBoxItemBaseStyle}">

</Style>
</hc:CheckComboBox.ItemContainerStyle>
</hc:CheckComboBox>

VM:
private List dataList;
public List DataList
{
get { return dataList; }
set { dataList = value;RaisePropertyChanged(); }
}
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A11", IsSelected = true });
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A111", IsSelected = true });
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A1111", IsSelected = true });
DataList.Add(new item() { Id = Guid.NewGuid(), Name = "A11111", IsSelected = false });

3.3.0版本下，前台显示正常，但3.4.0版本下，前台必须点一下才显示选中的项目。同时，如果后台数据全部为显示状态，则3.3.0和3.4.0都必须点一下才会显示

### Steps to reproduce the bug

新建xaml页面，绑定VM，使用prism框架

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by JiajunDou** [comment]
3.4.0-beta.36 依然没有修复这个问题

**Comment by JiajunDou** [comment]
临时方案：
`
comBox1.Loaded += (s, r) => {
                ((CheckComboBox)s).IsDropDownOpen=true;
                ((CheckComboBox)s).IsDropDownOpen = false;
            };
`

**Comment by NaBian** [comment]
在 456390b7 之后， 可使用 ```ListBoxAttach.SelectedItems```

**Comment by 54ble** [comment]
> 在 [456390b](https://github.com/HandyOrg/HandyControl/commit/456390b775c76afb60c86dfa8ae19d791c3a8a7f) 之后， 可使用 `ListBoxAttach.SelectedItems`

不在最新的包中，如何使用？
