### ISSUE TITLE
添加CirclePanel 中button时候加载StaticResource  CirclePanelButton时候报错, 找不到资源文件

### ISSUE THREAD

**Issue by kkouer** [NaBian/HandyControl#1321]
### Describe the bug

在添加完handycontrol 3.4.0后,在app.xaml中添加ResourceDictionary 并添加相应的CirclePanelButton的style后
在界面中添加CirclePanel 并添加button 设置为 Style="{StaticResource CirclePanelButton }"
运行报错

### Steps to reproduce the bug

1.加载handycontrol3.4.0
2.app.xaml添加ResoucreDictonary和Sytle
3.界面MainWindow.xaml中添加hc命名空间xmlns:hc="https://handyorg.github.io/handycontrol"
4.添加CirclePanel和6个button
5.运行后提示找不到资源 无法找到名为“CirclePanelDemoGeometry”的资源。资源名称区分大小写。

### Screenshots

![1](https://user-images.githubusercontent.com/12556230/206390030-f2543550-7d95-4d72-b8af-f164fec945d0.PNG)
![2](https://user-images.githubusercontent.com/12556230/206390040-5b74ef50-4712-4560-89a3-2d7d5da15fb7.PNG)
![3](https://user-images.githubusercontent.com/12556230/206390050-e1f1a91b-1938-4f2f-b489-074497e11c52.PNG)

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.7.2, .Net Framework 4.6.1

**Comment by NaBian** [comment]
你用的是 demo 中的样式。
