### ISSUE TITLE
PropertyGrid的double对应的NumberUpDown输入框无法输入小数

### ISSUE THREAD

**Issue by lwf163** [NaBian/HandyControl#1325]
### Describe the bug

PropertyGrid的double类型对应的NumberUpDown输入框无法输入小数
版本：3.4
换成3.3版本正常，只有3.4有这个问题

### Steps to reproduce the bug

暂时无法解决

### NuGet package version

None

**Comment by NaBian** [comment]
fixed in d0c14de6
