### ISSUE TITLE
[Feature request]3.4版本中Textbox不再支持ShowShowClearButton

### ISSUE THREAD

**Issue by EdmenGU** [NaBian/HandyControl#1338]
Nuget安装3.4.0之前的版本时 TextBox继承自System.Windows.Controls.TextBox, IDataInput.升级版本至3.4.0之后,TextBox继承自System.Windows.Controls.TextBox并且不再有ShowShowClearButton,想知道是转到其他扩展属性中了还是以后都不再提供该功能

**Comment by NaBian** [comment]
使用 infoelement 中的附加属性
