### ISSUE TITLE
Bug title托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“HandyControl!

### ISSUE THREAD

**Issue by AFei19911012** [NaBian/HandyControl#1343]
### Describe the bug

托管调试助手 "PInvokeStackImbalance"
  Message=托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“HandyControl!HandyControl.Tools.Interop.InteropMethods::GetWindowPlacement”的调用导致堆栈不对称。原因可能是托管的 PInvoke 签名与非托管的目标签名不匹配。请检查 PInvoke 签名的调用约定和参数与非托管的目标签名是否匹配。”

### Steps to reproduce the bug

更新到3.4.0，编译成功过，运行时报错

### NuGet package version

None

**Comment by EasyMaster2017** [comment]
我也遇到了同样的问题，仅仅是将HC从3.3.3升级到3.4，再重新调试运行就提示错误，编译没问题，运行出错。代码只根据XAML错误提示，将hc:TextBox的ShowClearButton改成hc:InfoElement.ShowClearButton，

**Comment by AFei19911012** [comment]
邮件已收到。

**Comment by NaBian** [comment]
现在问题是否已经解决？

**Comment by AFei19911012** [comment]
> 我也遇到了同样的问题，仅仅是将HC从3.3.3升级到3.4，再重新调试运行就提示错误，编译没问题，运行出错。代码只根据XAML错误提示，将hc:TextBox的ShowClearButton改成hc:InfoElement.ShowClearButton，

还有其它一些属性也去掉了，所以我还是更换成上一个版本了

**Comment by AFei19911012** [comment]
> 现在问题是否已经解决？

我还是更换为上一个版本了

**Comment by jojinshallar** [comment]
目标平台选x64不会有这个问题，x32在3.4版本会出现这个问题。应该是动态库声明有改动，参数位数未对齐。

**Comment by NaBian** [comment]
已在 dc50859c 中解决

**Comment by AFei19911012** [comment]
邮件已收到。
