### ISSUE TITLE
App sometimes gets cut when maximized

### ISSUE THREAD

**Issue by NotroDev** [NaBian/HandyControl#1345]
### Describe the bug

App sometimes gets cut in left top corner when maximized.

### Steps to reproduce the bug

1. Create window like this https://github.com/NotroDev/SkEditorPlus/blob/main/SkEditorPlus/MainWindow.xaml.cs
2. Minimize it
3. Maximize it by moving it to screen's top

### Screenshots

![image](https://user-images.githubusercontent.com/88681446/216437913-b4cc36e9-bbb8-4c72-a69f-eca22546d458.png)

### NuGet package version

HandyControls (Custom version) 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

### Additional context

HandyControls' version is 3.4.4, not 3.4.0

**Comment by NaBian** [comment]
3.4.4 非官方版本

**Comment by 4hera** [comment]
WindowStyle="None" worked for me
