### ISSUE TITLE
无法控制小数点

### ISSUE THREAD

**Issue by Zero-net-oss** [NaBian/HandyControl#1346]
在数值里面，一旦设置有小数点的值，就会导致数值输入不了，也无法删除

**Comment by zh3305** [comment]
我也出现同样问题. 版本3.4.0   _ net7
在使用了 Value="{Binding xxx}" 的情况下   ValueFormat="N2"  DecimalPlaces="2"  都会出现这种情况 不设置小数位正常,但无法输入小数

![动画](https://user-images.githubusercontent.com/6190168/217196317-ebd9db59-8906-4baa-a787-fd1e6be9a017.gif)

**Comment by zh3305** [comment]
已测试 在3.4.0 分支 的NumericUpDown 有此问题,在最新master 分支中无此问题 
fix by #1292 

请关闭Issues

**Comment by NaBian** [comment]
fixed by d0c14de6063e92f74dab9ddaee1cb0523574dd10

**Comment by boogaloo-jw** [comment]
> 已测试 在3.4.0 分支 的NumericUpDown 有此问题,在最新master 分支中无此问题 fix by #1292
> 
> 请关闭Issues

请问现在并没有release新版本，项目中如何使用啊？nuget包里依然是3.4.0版本，NumericUpDown还是有这个问题！
