### ISSUE TITLE
FileNotFoundException:未能正确加载文件或程序集“HandyControl”

### ISSUE THREAD

**Issue by Leon-lu** [NaBian/HandyControl#1350]
### Describe the bug

.net版本为“net45”,项目类型为“类库”，新建空白窗体，提示未能正确加载程序集，经过测试必须添加“hc:Shield”和对应的“click”事件，程序运行正常，

### Steps to reproduce the bug

1. 第三方程序加载“dll”,比如“AutoCad”
2. 创建窗体并显示“new Window1().Show();”
3. 程序抛出异常
备注：
经过测试与试验，只有在添加“hc:Shield”控件同时必须添加对应的“Click”事件，程序可以正常运行，着实费解

### Screenshots

xaml代码
![image](https://user-images.githubusercontent.com/79854911/218386511-9540b45d-11fc-4c2a-813b-2ec2da7a4935.png)
异常截图
![image](https://user-images.githubusercontent.com/79854911/218386232-cb0ac7e0-22f1-45f8-9cab-4d22f0860cec.png)

经过修改可以正常运行的xaml代码与运行截图
![image](https://user-images.githubusercontent.com/79854911/218386728-c964dccc-40f3-4035-8119-cb28f08f200b.png)

![image](https://user-images.githubusercontent.com/79854911/218386749-aaada747-b21a-4e76-b4d6-df22999c05be.png)

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

**Comment by 7urnin** [comment]
试试刚开始的时候先编译生成一下，这样子应该就能直接用了
