### ISSUE TITLE
[Feature request]TextBox 和 PasswordBox 支持IconElement

### ISSUE THREAD

**Issue by 204065248** [NaBian/HandyControl#1351]
**Is your feature request related to a problem? Please describe.**
日常开发常见的INPUT框带ICON，但是我试了试他们两个都不支持icon。

**Describe the solution you'd like**
支持添加ICON，可以左边显示也可以右边显示

**Describe alternatives you've considered**
我目前使用border + grid 包起来解决icon的

**Comment by NaBian** [comment]
可尝试 `ElementGroup`
![image](https://user-images.githubusercontent.com/17383395/218752728-37df0169-b001-4086-817a-b6f46d344ae8.png)

**Comment by 204065248** [comment]
好的
