### ISSUE TITLE
TagContainer通过ItemsSource绑定生成的Tag的ShowCloseButton属性默认为True

### ISSUE THREAD

**Issue by xiaoheigege** [NaBian/HandyControl#1355]
在用TagContainer绑定生成Tag时 这些Tag的ShowCloseButton属性默认为true，希望可以给TagContainer添加一个属性用来指示生成的Tag是否允许删除，从而匹配不同的需求

**Comment by aierong** [comment]
绑定一下,就可以实现你要的:

`            <hc:TagContainer Width="420"
                             Margin="11"
                             Padding="5"
                             ItemContainerStyle="{StaticResource TagCustomStyle}"
                             ItemsSource="{Binding Students}" />`



`    <UserControl.Resources>
        <Style x:Key="TagCustomStyle"
               BasedOn="{StaticResource TagBaseStyle}"
               TargetType="hc:Tag">
            <Setter Property="Content" Value="{Binding Name}" />
            <Setter Property="Margin" Value="5" />
            <Setter Property="IsSelected" Value="{Binding IsSelected}" />
            <Setter Property="ShowCloseButton" Value="{Binding ShowCloseButton}" />
        </Style>
    </UserControl.Resources>`
