### ISSUE TITLE
`NumericUpDown` not accept user input while `ValueFormat="P2"`

### ISSUE THREAD

**Issue by GF-Huang** [NaBian/HandyControl#1362]
### Describe the bug

When I try to type the value manually rather than click increase button, it seems ignore my input.

![mmOvHUvCOF](https://user-images.githubusercontent.com/4510984/222266624-c2e80c85-8dcb-49ab-8785-b4dce26c2579.gif)

### Steps to reproduce the bug

```xaml
<hc:NumericUpDown Style="{StaticResource NumericUpDownPlus}"
                  Value="{Binding DecimalProperty, UpdateSourceTrigger=PropertyChanged}"
                  ValueFormat="P2" Minimum="0" Increment="0.0005" />
```

Binding to a `double` property issue still, seems not the type issue.

### Expected behavior

The `NumericUpDown.Value` should be the value what I type.

### NuGet package version

HandyControls (Custom version) 3.4.4

### IDE

Visual Studio 2022

### Framework type

.Net 7.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
NumericUpDown does not support this at the moment. You can use the following alternative:
![image](https://user-images.githubusercontent.com/17383395/226113048-2be97d86-a54f-43a3-8f1d-3751f8e355af.png)
``` xaml
<hc:ElementGroup Layout="Stack" VerticalAlignment="Center" HorizontalAlignment="Center">
    <hc:NumericUpDown hc:TitleElement.Title="百分比" Style="{StaticResource NumericUpDownPlus}" hc:TitleElement.TitlePlacement="Left" MinWidth="320" VerticalAlignment="Center" Increment="0.0005" />
    <Border BorderThickness="1" BorderBrush="{DynamicResource BorderBrush}">
        <TextBlock Text="%" VerticalAlignment="Center" Padding="8 0"/>
    </Border>
</hc:ElementGroup>
```
