### ISSUE TITLE
Transfer 穿梭框无法获取右列被选取的项目

### ISSUE THREAD

**Issue by zch1661** [NaBian/HandyControl#1368]
### Describe the bug

使用Transfer 穿梭框时，当项目被选中传递到右侧列表时，无论右侧列表中的项目是否被选中，均无法获取到被传递过去的的项目，SelectedItems为null。
当左侧列表的某些项目被选中时，能够获取SelectedItems，此时其内容为左列中被选中的项目。

### Steps to reproduce the bug

新建一个WPF项目，NuGet添加HandyControl，添加添加Transfer 穿梭框即可。
无论是否MVVM模式，均无法获取。

### NuGet package version

HandyControl 3.4.0

**Comment by NaBian** [comment]
使用 TransferredItems

**Comment by NaBian** [comment]
使用 TransferredItems
