### ISSUE TITLE
自己摸索太折磨了，有没有交流群求进，官网的QQ群挂了

### ISSUE THREAD

**Issue by 1CDE683405CAC00EAD7242DCD02BC0AB** [NaBian/HandyControl#1384]
各位大佬，这个UI库有没有官方交流群啊，最近两天用了一下，各种不会用，想要局部定义一个样式，老是被这个UI库全局样式覆盖，太折磨了，求个群讨论一下，官网挂的两个QQ群好像挂了

**Comment by Roger12340** [comment]
> 各位大佬，这个UI库有没有官方交流群啊，最近两天用了一下，各种不会用，想要局部定义一个样式，老是被这个UI库全局样式覆盖，太折磨了，求个群讨论一下，官网挂的两个QQ群好像挂了

可以加我QQ：912950735

**Comment by NaBian** [comment]
以前有，后来解散了，嫌麻烦。
