### ISSUE TITLE
Dialog.Show()的关闭有bug

### ISSUE THREAD

**Issue by guolunya** [NaBian/HandyControl#1385]
### Describe the bug

当主程序窗口出现遮罩层时，被其他窗体遮罩了，遮罩层永远不会关闭。

### Steps to reproduce the bug

public async void Close()
      {
         var isLooper = true;
         FrameworkElement value;
         if (string.IsNullOrEmpty(_token))
         {
            var win = WindowHelper.GetActiveWindow();
            if (win == null)
            {
               while (isLooper) 
               {
                  await Task.Delay(10);
                  win = WindowHelper.GetActiveWindow();
                  if (win != null)
                  {
                     isLooper = false;
                  }
               }
            }
            Close(WindowHelper.GetActiveWindow());
         }
         else if (ContainerDic.TryGetValue(_token, out value))
         {
            Close(value);
         }
      }

这是我写的修复代码，可能不是太对，希望官方把这个bug修复掉

### NuGet package version

None

**Comment by NaBian** [comment]
使用 token 解决你的问题。
