### ISSUE TITLE
[Feature request] Enable AutoReverse of RunningBlock if Runaway is false

### ISSUE THREAD

**Issue by moomiji** [NaBian/HandyControl#1389]
**Is your feature request related to a problem? Please describe.**
目前滚动块设置Runaway = False时，会将AutoReverse覆盖为True，滚动块的内容默认会触底后反弹。

**Describe the solution you'd like**
希望滚动块设置Runaway = False、AutoReverse=False时，滚动内的内容可以不断地往一个方向滚动。

**Comment by NaBian** [comment]
默认就是你要的效果
