### ISSUE TITLE
[Bug report] If "PART_TextBox" is focused, the text remains unchanged after clicking the up or down button in NumericUpDown.

### ISSUE THREAD

**Issue by moomiji** [NaBian/HandyControl#1395]
### Describe the bug

当NumericUpDown 中点击向上或向下按钮时，如果焦点在"PART_TextBox"，显示的Text将保持不变。

由 https://github.com/HandyOrg/HandyControl/commit/d0c14de6063e92f74dab9ddaee1cb0523574dd10 导致

**Comment by NaBian** [comment]
fixed in 3e01876f
