### ISSUE TITLE
TabControl嵌套使用时内部TabControl行为不正确

### ISSUE THREAD

**Issue by DongLinZhu** [NaBian/HandyControl#1399]
### Describe the bug

TabControl嵌套使用时，内部tab会随着外部tab的切换而切换

### Steps to reproduce the bug

1、嵌套使用TabControl，且至少包含两个tabItem
2、使用样式`Style="{StaticResource TabControlInLine}"`
3、重复切换外部tab即可看到内部tab的异常行为

### Expected behavior

切换外部tab时保留内部选择的tab

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by jzjwonderful** [comment]
该问题在3.5.1版本中依然存在。
