### ISSUE TITLE
Why TextBox not support IsError, ErrorStr, VerifyFunc?

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1402]
The documentation says that `IsError`, `ErrorStr`, `VerifyFunc` are supported, but these properties are not actually available.

**Comment by CD89757** [comment]
我也是昨天发现的这个问题，新版里没有继承 IDataInput，但是文档上有，而且3.1版本继承了这个接口，但是这几个属性都没效果

**Comment by NaBian** [comment]
已删除此支持，请使用 wpf 自带验证机制。
