### ISSUE TITLE
InfoElement.RegexPattern not work, TextType readonly

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1403]
### Describe the bug

`InfoElement.RegexPattern` not work.
`TextType` is readonly property, can not set value.

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
pls use https://github.com/HandyOrg/HandyControl/blob/4206bfd61ccb48d6e6896dcdef66a96f51b698b2/src/Shared/HandyControlDemo_Shared/UserControl/Controls/TextBoxDemoCtl.xaml#L21
