### ISSUE TITLE
为什么引用HandyControl中的样式必须生成之后才能看到效果？

### ISSUE THREAD

**Issue by adriel2012** [NaBian/HandyControl#1413]
### Describe the bug

很早之前就发现的一个问题，我在开发的过程中，例如使用Style="{StaticResource ButtonInfo}"来引用HandyControl中的预定义样式，Button控件的外观是不能即时显示出效果的，这段代码下方还会被标记波浪线，也就是警告提示，必须生成项目之后，引用的样式才能正常生效。我同样尝试了谷歌的MaterialDesign包，发现没有类似的问题，引用样式是可以立即显示出来的，我查了很久，一直不知道问题在哪里

### Steps to reproduce the bug

Button控件的Style="{StaticResource ButtonInfo}"

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
hc 使用了样式压缩，可加快样式读取速度，提高程序性能，代价是可能对设计器不友好。

**Comment by adriel2012** [comment]
> 
原来是这样，感谢回复
