### ISSUE TITLE
Carousel -The picture cannot be fully displayed

### ISSUE THREAD

**Issue by javaCR7** [NaBian/HandyControl#1440]
![image](https://github.com/HandyOrg/HandyControl/assets/38103065/06b89d08-00d9-4dec-b062-d64219a3c090)
the picture can not be fully displayed。Only when the height and width of the control are set to the same as the image can it be displayed normally 。
![image](https://github.com/HandyOrg/HandyControl/assets/38103065/abfd9583-0a2c-4240-8ffc-f726337be80c)

**Comment by 810906591** [comment]
System.ArgumentOutOfRangeException:“Specified argument was out of the range of valid values. Arg_ParamName_Name”
