### ISSUE TITLE
DateTimePicker 初始值为 null时

### ISSUE THREAD

**Issue by iexapl** [NaBian/HandyControl#1441]
### Describe the bug

DateTimePicker 初始值为 null时，显示是当前时间，可对控件不做任何操作，得到的值还是初始值，也就是说显示值与实际获取到的值不一致（使用的Prism MVVM 绑定的值）

### Steps to reproduce the bug

如题描述

### Expected behavior

增加一个操作属性，当初始值为 null时，是否自动置为当前时间。若为：否，则还是 null，显示应该是空的（与清空时显示效果一样）；反之，将显示时间与实际取值置为当前时间

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
自动设置为当前时间感觉没啥必要，删掉吧。
