### ISSUE TITLE
发布一个新版本吧

### ISSUE THREAD

**Issue by mghcool** [NaBian/HandyControl#1442]
好久没有发布新版本了，nuget上的版本太陈旧了，可不可以发布一个新版本？

**Comment by Anonymy** [comment]
坐等

**Comment by BOYMMM** [comment]
同求，谢谢

**Comment by guanguanchuangyu** [comment]
可以看看预览版本 通过访问myget地址：
https://www.myget.org/F/handycontrol/api/v3/index.json
这个地址一般是发布的预发布版本。

**Comment by sunxiaotianmg** [comment]
期待更新一个新版本

**Comment by NaBian** [comment]
done
