### ISSUE TITLE
ListBox 无法虚拟化

### ISSUE THREAD

**Issue by cuiliang** [NaBian/HandyControl#1452]
### Describe the bug

由于在模板中对ScrollViewer设置了`CanContentScroll="false"`，造成了ListBox 无法虚拟化，当列表条目数量较多时会非常卡顿。

[                                <hc:ScrollViewer IsInertiaEnabled="{Binding Path=(hc:ScrollViewer.IsInertiaEnabled),RelativeSource={RelativeSource TemplatedParent}}" CanContentScroll="false" Focusable="false" HorizontalScrollBarVisibility="{TemplateBinding ScrollViewer.HorizontalScrollBarVisibility}" Padding="{TemplateBinding Padding}" SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}" VerticalScrollBarVisibility="{TemplateBinding ScrollViewer.VerticalScrollBarVisibility}">](https://github.com/HandyOrg/HandyControl/blob/cb660054792ba9a3d9a660ec9a2deac75f321513/src/Shared/HandyControl_Shared/Themes/Styles/Base/ListBoxBaseStyle.xaml#L82)

还有不少地方设置了这个属性，不清楚是否也存在类似的影响：
https://github.com/search?q=repo%3AHandyOrg%2FHandyControl%20CanContentScroll%3D%22false%22&type=code

### Steps to reproduce the bug

~

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.7.2

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
可以全部删除，但是 `IsInertiaEnabled` 属性可能不生效，需要配合 `CanContentScroll="false"` 才能起作用，不过相对于虚拟化，`IsInertiaEnabled` 倒是不算什么。
