### ISSUE TITLE
ToggleBlock 内存泄露

### ISSUE THREAD

**Issue by cuiliang** [NaBian/HandyControl#1461]
### Describe the bug

发现ToggleBlock会导致内存泄露。

![image](https://github.com/HandyOrg/HandyControl/assets/1972649/17f81ff2-6aa4-415e-91d1-344409920e93)

尝试Demo，也有类似问题：

![image](https://github.com/HandyOrg/HandyControl/assets/1972649/3744a759-1c81-4178-8e61-85cba586b22c)

### Steps to reproduce the bug

启动Demo，使用DotMemory多次快照并对比。

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8, .Net Framework 4.7.2

**Comment by cuiliang** [comment]
这样似乎可以解决，供大佬参考。
<img width="604" alt="81289ab56d50bce4a6454405e22e24c6" src="https://github.com/HandyOrg/HandyControl/assets/1972649/20374644-8267-44d7-8b8e-7c0e3b0e1e01">

**Comment by cuiliang** [comment]
另外，可能是因为使用MouseGesture的原因，有时候点击ComboBox不会展开下拉框。
我目前的处理方法是在OnToggleGestureChanged里写一个是否需要触发下拉的标记，然后继承OnMouseLeftButtonDown方法，在这个标记启用的时候切换IsChecked。

https://github.com/cuiliang/HandyControl/blob/master/src/Shared/HandyControl_Shared/Controls/Block/ToggleBlock.cs#L76

**Comment by GF-Huang** [comment]
@NaBian commit 8e1e826 疑似产生了这个问题：https://github.com/ghost1372/HandyControls/issues/213

**Comment by DineshSolanki** [comment]
> In addition, maybe because of the use of MouseGesture, sometimes clicking the ComboBox will not expand the drop-down box. My current method is to write a tag in OnToggleGestureChanged to determine whether the drop-down needs to be triggered, and then inherit the OnMouseLeftButtonDown method to switch IsChecked when the tag is enabled.
> 
> [cuiliang/HandyControl@ `master`/src/Shared/HandyControl_Shared/Controls/Block/ToggleBlock.cs#L76 ](https://github.com/cuiliang/HandyControl/blob/master/src/Shared/HandyControl_Shared/Controls/Block/ToggleBlock.cs?rgh-link-date=2023-09-24T13%3A49%3A09Z#L76)

this happens, with the combobox dropdown auto closes and only is open until I don't lift mouse button,

https://github.com/HandyOrg/HandyControl/issues/1467
