### ISSUE TITLE
DateTimePicker 区分代码修改 和视图修改的change事件

### ISSUE THREAD

**Issue by shiyuanGame** [NaBian/HandyControl#1462]
比如说我又一排预定义的时间选择按钮 当天 一周 一个月，我点击按钮会同步时间到日期选择的SelectedDateTime，
会触发change事件 但是我这时候不想触发change事件 ，我又想要从视图修改 这个要触发change事件 需要触发查询事件

**Comment by NaBian** [comment]
通过引入状态变量可实现你的需求。
