### ISSUE TITLE
突然不可以启动

### ISSUE THREAD

**Issue by carpONE** [NaBian/HandyControl#1479]
### Describe the bug

一开始创建使用后可以，经过一段时间没用后再运行出现如下情况：
托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“HandyControl!HandyControl.Tools.Interop.InteropMethods::GetWindowPlacement”的调用导致堆栈不对称。原因可能是托管的 PInvoke 签名与非托管的目标签名不匹配。请检查 PInvoke 签名的调用约定和参数与非托管的目标签名是否匹配。”

### Steps to reproduce the bug

经过一段时间没用再运行后就会出现

### Screenshots

![image](https://github.com/HandyOrg/HandyControl/assets/81232339/b3bb1276-0d01-4b90-86f9-2f8661d47553)

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
fixed in 3.5 dc50859ceee4af9e649ec341de90eca9cbf737cb
