### ISSUE TITLE
请求nuget包发布更新到最新

### ISSUE THREAD

**Issue by zhudk** [NaBian/HandyControl#1485]
### Feature request type

sample request

### Is your feature request related to a problem? Please describe

现在nuget上的3.4是22年的，NumericUpDown控件在删除输入数值是光标位置异常。辛苦大神给发布个最新的~

### Describe the solution you'd like

现在nuget上的3.4是22年的，NumericUpDown控件在删除输入数值是光标位置异常。辛苦大神给发布个最新的~

**Comment by NaBian** [comment]
预计年前。

**Comment by NaBian** [comment]
done
