### ISSUE TITLE
处于禁用时 TextBoxPlusBaseStyle 的 Title 颜色效果没有变化

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1488]
触发器似乎忘记处理 Title 了，导致界面整体禁用（`IsEnabled=False`）变灰后，Title 的文字仍然很显眼。
此问题包括 `ReadOnlyComboBox` 及任何支持 `hc:TitleElement.Title` 的控件。

https://github.com/HandyOrg/HandyControl/blob/babf40e59fe9e57eb185e4658ce46036610083f9/src/Shared/HandyControl_Shared/Themes/Styles/Base/TextBoxBaseStyle.xaml#L194

**Comment by NaBian** [comment]
设计如此
