### ISSUE TITLE
`ExtendContentToNonClientArea` not work as expected

### ISSUE THREAD

**Issue by GF-Huang** [NaBian/HandyControl#1494]
### Describe the bug

When set `hc:WindowAttach.ExtendContentToNonClientArea="True"`, the non-client area cover the client content.

![image](https://github.com/HandyOrg/HandyControl/assets/4510984/8e94565b-bf05-42cf-8d08-399f27ca635a)

### Steps to reproduce the bug

Code for reproduce:

```cs
<hc:Window x:Class="HandyControlProject1.Views.RootView"
           ...
           hc:WindowAttach.ExtendContentToNonClientArea="True">
  <Grid Background="Green">
    <TextBlock Text="123456" Foreground="Black" FontSize="50" />
  </Grid>
</hc:Window>
```

### NuGet package version

HandyControls (Custom version) 3.5.0

### IDE

Visual Studio 2022

### Framework type

.Net 8.0

### Windows version

Windows 11 22H2 22621.2715

**Comment by NaBian** [comment]
设计如此，可以使用 `NonClientAreaBackground="Transparent"` 将底部内容显示。
