### ISSUE TITLE
hc:TitleElement.MarginOnTheTop not found

### ISSUE THREAD

**Issue by CodingOctocat** [NaBian/HandyControl#1498]
### Describe the bug

hc:TitleElement.MarginOnTheTop not found.

### Steps to reproduce the bug

重写 `TextBoxPlusTopTemplate` 样式时，发现缺少 `hc:TitleElement.MarginOnTheTop` 属性，但我看 GitHub 代码库中是存在的.

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
3.4 版本不支持。
