### ISSUE TITLE
把WPF项目从.NET Framework 4.8通过Visual Studio的Upgrade选项升级到.NET 8.0后，某些页面出现崩溃问题

### ISSUE THREAD

**Issue by adriel2012** [NaBian/HandyControl#1504]
### Describe the bug

经过我一段时间的排查，发现只要是使用了ListBox、Combobox、DataGrid控件的界面，跳转到这些界面的时候就会报这个异常，我尝试把这些控件通过Style={x:Null}屏蔽掉HandyControl的全局默认样式之后，异常就不会再出现了。

另外，我尝试新建了一个.NET 8.0的测试项目，引用了HandyControl，并且在测试的界面中添加了ListBox、Combobox、DataGrid控件，发现一切正常，没有出现上面提到的异常。这是什么原因？我该如何解决这个问题？

### Steps to reproduce the bug

我的程序就是，点击主界面的某一个按钮，跳转到相应的子界面，然后就出现异常了

### Screenshots

![Snipaste_2023-12-28_14-01-28](https://github.com/HandyOrg/HandyControl/assets/3355292/f77d4ad0-92dc-4f5b-bbf3-1f82515993f0)

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22000)

**Comment by NaBian** [comment]
8d4d11309fde22e39a02f0ddda6bc9ac57aca01a
