### ISSUE TITLE
Chinese  Language Changes to English  Language

### ISSUE THREAD

**Issue by zhengcw520** [NaBian/HandyControl#1510]
### Describe the bug

The DateTimePicker are displayed in CN language, when I use "ConfigHelper.Instance.SetLang("en");
The Pagination Jump are displayed in CN language, when I use "ConfigHelper.Instance.SetLang("en");

### Steps to reproduce the bug

1.when I use "ConfigHelper.Instance.SetLang("en"); The DateTimePicker AM ,PM and Confirm are displayed in CN language

### Screenshots

![image](https://github.com/HandyOrg/HandyControl/assets/24794329/9f36a241-7244-4dc5-86dc-9f7a1b639d72)

### NuGet package version

HandyControl 3.4.0

### IDE

VS2022

### Framework type

.net6.0

### Windows version

Windows10

**Comment by zhengcw520** [comment]
The Pagination Jump are displayed in CN language, when I use "ConfigHelper.Instance.SetLang("en");  
this question can change  style to solute.

**Comment by NaBian** [comment]
英文不是 HC 默认语言，需要到 nuget 下载额外的语言包：[HC 英文包](https://www.nuget.org/packages/HandyControl.Lang.en)

**Comment by zhengcw520** [comment]
已经解决，谢谢

**Comment by society2012** [comment]
ConfigHelper.Instance.SetLang("en") 我下载了语言包也没生效，messagebox按钮还是显示中文
