### ISSUE TITLE
未在类型“IconElement”中找到可附加的属性“Geometry”

### ISSUE THREAD

**Issue by quzefeng** [NaBian/HandyControl#1512]
### Describe the bug

管理员：
您好，我第一次使用咱们的框架，但是现在基础的功能都引入了，但是给按钮特殊的样式，系统无法正常运行； controls:BorderElement.CornerRadius="15"
开发工具是VS2022;
运行环境是.NET 8;
操作系统是WIN10;
请帮助指点我应该如何处理；
![111](https://github.com/HandyOrg/HandyControl/assets/17823304/32a4ae3e-81e3-4b22-90ba-77ae894b10b6)
![222](https://github.com/HandyOrg/HandyControl/assets/17823304/95afb7a0-72c8-4cd1-bec2-d439f23d1901)
![333](https://github.com/HandyOrg/HandyControl/assets/17823304/1de676b0-cd46-446f-a4b0-ba8651170ddb)

### Steps to reproduce the bug

管理员：
您好，我第一次使用咱们的框架，但是现在基础的功能都引入了，但是给按钮特殊的样式，系统无法正常运行； controls:BorderElement.CornerRadius="15"
开发工具是VS2022;
运行环境是.NET 8;
操作系统是WIN10;
请帮助指点我应该如何处理；

### Expected behavior

第一步
下载源码或者以Nuget的方式引用控件库。
源码链接：HandyControl-Github
Nuget链接：HandyControl-Nuget

第二步
在App.xaml中添加以下代码：

<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml"/>
            <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
第三步
添加命名空间：xmlns:hc="https://handyorg.github.io/handycontrol"

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

Windows 11 (22000)

**Comment by quzefeng** [comment]
![5](https://github.com/HandyOrg/HandyControl/assets/17823304/99dd5ba4-d785-400d-977b-d3b0029a96a9)
![6](https://github.com/HandyOrg/HandyControl/assets/17823304/66137b28-5537-41a1-af31-27dd9f70f41c)

**Comment by yll690** [comment]
命名空间不对，前面都知道写hc，为什么到后面又要用controls

**Comment by wangjunjx8868** [comment]
> 命名空间不对，前面都知道写hc，为什么到后面又要用controls

这个controls 是文档有这个写法

**Comment by NaBian** [comment]
> 命名空间不对，前面都知道写hc，为什么到后面又要用controls
