### ISSUE TITLE
在引用HandyControl的项目中修改DefaultCornerRadius不起作用，因为它总是通过StaticResource引用

### ISSUE THREAD

**Issue by yll690** [NaBian/HandyControl#1515]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

在引用HandyControl的项目中修改DefaultCornerRadius不起作用

### Describe the solution you'd like

所有使用DefaultCornerRadius资源的控件样式中都是通过StaticResource来引用的，为什么不用DynamicResource呢？

**Comment by NaBian** [comment]
颜色、字体是常用的样式更改项，所以支持动态调整，但圆角不常用，一般需要通过重启软件实现圆角修改，故不适合使用动态资源。

**Comment by yll690** [comment]
@NaBian 那么在通过nuget包引用handycontrol时，如何在程序中修改默认圆角？在窗口或者App中添加`<CornerRadius x:Key="DefaultCornerRadius">20</CornerRadius>`是没有效果的
