### ISSUE TITLE
[BUG] ListViemItems are not rendered

### ISSUE THREAD

**Issue by rampaa** [NaBian/HandyControl#1524]
### Describe the bug

After upgrading my project from HandyControl 3.4.0 to 3.5.0, I noticed that ListViewItems are not being rendered at all.

### Steps to reproduce the bug

1) Create a new WPF project
2) Add HandyControl 3.5.0 to the created project
3) Make sure to add `<ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml" />` inside your App.xaml.
4) Add a ListView with some ListViewItems to your MainWindow.xaml like the following:
```C#
<ListView>
    <ListViewItem Visibility="Visible">
        Item 1
    </ListViewItem>
    <ListViewItem>
        Item 2
    </ListViewItem>
</ListView>
```
5) Notice that how you only see a blank window and the ListViewItems are not being shown at all. Setting the visibility of ListViewItems does not seem to affect anything either.

### Expected behavior

ListViewItems should be rendered.

### NuGet package version

None

### IDE

Visual Studio 2022-preview

### Framework type

.Net 6.0

### Windows version

May 2021 Update (19043)

### Additional context

Using a ListBox instead of ListView will work. But for whatever reason, ListBox's virtualization capabilities seem to be broken for me so I do have to use a ListView.

**Comment by ErickWei** [comment]
i have the same issue after upgrade to 3.5.0
