### ISSUE TITLE
Error after updating from 3.4.5 to 3.5.0

### ISSUE THREAD

**Issue by candinho87** [NaBian/HandyControl#1526]
### Describe the bug

`The invocation of the constructor in type 'HandyControl.Controls.ToggleBlock' that matches the specified binding constraints threw an exception`

### Steps to reproduce the bug

add handy controls nugget, place some controls on a wpf window and run the aplication

### Expected behavior

work

### NuGet package version

None

### IDE

Visual Studio 2022

### Additional context

work as spected on 3.4.5

**Comment by dbalickwellnet** [comment]
I am also getting this.

**Comment by Soar360** [comment]
me too.

**Comment by hisaner** [comment]
meet too. adding the ComboBox  control will also cause this issue.
