### ISSUE TITLE
3.5 版本的PasswordBox不能使用ShowClearButton

### ISSUE THREAD

**Issue by glqf** [NaBian/HandyControl#1527]
### Describe the bug

无法识别或访问成员“ShowClearButton”。未在类型“PasswordBox”中找到属性“ShowClearButton”。	

### Steps to reproduce the bug

<hc:PasswordBox ShowClearButton="True" />

### Screenshots

![123](https://github.com/HandyOrg/HandyControl/assets/46473050/eb1155b3-c430-44f8-9712-a917ef72f467)

### NuGet package version

None

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22000)

**Comment by glqf** [comment]
好吧，3.5的demo改成hc:InfoElement.ShowClearButton="True"

**Comment by By-lixiuming** [comment]
为啥我添加了hc:InfoElement.ShowClearButton="True"这个但是没有clear按钮显示
