### ISSUE TITLE
DateTimePicker hc:InfoElement相关异常

### ISSUE THREAD

**Issue by samueltian666** [NaBian/HandyControl#1531]
### Describe the bug

<hc:TextBox  hc:InfoElement.Placeholder="xxx"  hc:InfoElement.ShowClearButton="True" />
//hc:InfoElement 相关的一切正常
<hc:DateTimePicker hc:InfoElement.TitlePlacement="Left"  hc:InfoElement.Title="xxxxx" hc:InfoElement.Placeholder="xxxx"  hc:InfoElement.ShowClearButton="True" Margin="5 0 5 0"/>
//DateTimePicker TimePicker hc:InfoElement 相关的一切不正常
//DatePicker 的却正常    
//降级3.4也没用
//x64 anycpu切换也没用

### Steps to reproduce the bug

0

### Expected behavior

0

### NuGet package version

HandyControl 3.4.0

### IDE

Visual Studio 2022

### Framework type

.Net 6.0

### Windows version

May 2021 Update (19043)

**Comment by ZIDSHXIU** [comment]
请为DateTimePicker控件设置该Style：Style="{StaticResource DateTimePickerPlus}"。

**Comment by NaBian** [comment]
> 请为DateTimePicker控件设置该Style：Style="{StaticResource DateTimePickerPlus}"。
