### ISSUE TITLE
希望可以提供方法直接切换主题/主题色

### ISSUE THREAD

**Issue by luluxiaoyu** [NaBian/HandyControl#1541]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

切换主题的时候需要更新资源字典如
internal void UpdateSkin(SkinType skin)
        {
             Resources.MergedDictionaries.Clear();
            Resources.MergedDictionaries.Add(new ResourceDictionary
            {
                Source = new Uri($"pack://application:,,,/HandyControl;component/Themes/Skin{skin.ToString()}.xaml")
            });
            Resources.MergedDictionaries.Add(new ResourceDictionary
            {
                Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
            });
        }

### Describe the solution you'd like

希望能提供类似的直接切换主题/主题色的方法
如：
                BrushConverter brushConverter = new BrushConverter();
                ThemeManager.Current.AccentColor = (Brush)brushConverter.ConvertFromString("#0078D4");

**Comment by followtheart** [comment]
这个功能实现了吗？

**Comment by luluxiaoyu** [comment]
> 这个功能实现了吗？

我记得是handycontrols有这个功能
带s的那个
