### ISSUE TITLE
Version 3.5.2 cannot be found on NuGet

### ISSUE THREAD

**Issue by rampaa** [NaBian/HandyControl#1584]
Even though the version was bumped to 3.5.2 in https://github.com/HandyOrg/HandyControl/commit/895a3f0611886bc8ccb2c90dcb418deff639ddd8, the latest version that can be found on NuGet is 3.5.1. I am not sure if this is intentional or not, if it's intentional please feel free to close this issue.

**Comment by ghost1372** [comment]
@rampaa  original 3.5.2 does not published yet, however if you need latest changes, you can use unofficial version:
https://www.nuget.org/packages/HandyControls
