### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by o-medizadeh-Ard** [NaBian/HandyControl#1586]
### Describe the bug

the Growl with prameter 'ShowPersianDateTime = true,' has the following error on date '05/18/2024' :
System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.'
But it works correctly on other dates.

### Steps to reproduce the bug

error

### Expected behavior

error

### NuGet package version

None

### IDE

Visual Studio 2019

### Framework type

.Net 5.0

### Additional context

error

**Comment by ghost1372** [comment]
fixed in https://github.com/ghost1372/HandyControls/commit/905d65b5f6362d47c4ee5d645b01da3f135027a9

**Comment by o-medizadeh-Ard** [comment]
> fixed in [ghost1372/HandyControls@905d65b](https://github.com/ghost1372/HandyControls/commit/905d65b5f6362d47c4ee5d645b01da3f135027a9)

ok, Thanks.
But the package that is downloaded from 'Nuget' has not been fixed yet and this bug still remains on the latest version 3.5.2.
Thank

**Comment by o-medizadeh-Ard** [comment]
Thanks.
I have downloaded and installed the latest '3.5.2' package from nugget.
Please guide me how to use your bug fix commit?
