### ISSUE TITLE
`hc:ListBoxAttach.SelectedItems` binding got `null`

### ISSUE THREAD

**Issue by GF-Huang** [NaBian/HandyControl#1599]
### Describe the bug

https://github.com/HandyOrg/HandyControl/assets/4510984/a7ecdee8-7ce4-42f8-86dd-7c45959c71a3

### Steps to reproduce the bug

Codes to reproduce

```xaml
<hc:Window ...>
  <hc:CheckComboBox VerticalAlignment="Center" HorizontalAlignment="Center" Width="300"
                    ItemsSource="{Binding DataList}" hc:ListBoxAttach.SelectedItems="{Binding SelectedDataItems}" />
</hc:Window>

```
```cs
public class RootViewModel : PropertyChangedBase {
    public IReadOnlyList<string> DataList { get; } = ["1", "2", "3"];

    public List<string> SelectedDataItems { get; set; } = [];
}
```
[CheckComboBoxDemo.zip](https://github.com/HandyOrg/HandyControl/files/15463823/CheckComboBoxDemo.zip)

### NuGet package version

HandyControl 3.5.1

### IDE

Visual Studio 2022

### Framework type

.Net 8.0

### Windows version

Windows 11 23H2

**Comment by GF-Huang** [comment]
Solved by change `List<string> SelectedDataItems` to `IList SelectedDataItems`.

**Comment by blackvon-sudo** [comment]
> Solved by change `List<string> SelectedDataItems` to `IList SelectedDataItems`.

It's not worked

**Comment by GF-Huang** [comment]
> > Solved by change `List<string> SelectedDataItems` to `IList SelectedDataItems`.
> 
> It's not worked

Make sure it is `IList` not `IList<T>`.
