### ISSUE TITLE
SearchBar不显示Placeholder

### ISSUE THREAD

**Issue by rocascent** [NaBian/HandyControl#1652]
### Describe the bug

![图片](https://github.com/user-attachments/assets/1f8cadd6-2db6-43e6-a50e-7cb8470834ed)
```xaml
<hc:SearchBar hc:InfoElement.Placeholder="placeholder"/>
```

### Steps to reproduce the bug

run HandyControl demo.

### NuGet package version

None

### IDE

Visual Studio 2022

### Windows version

Windows 11 (22000)

### Additional context

3.5.1 版本

**Comment by ABA2396** [comment]
使用 Placeholder 需要指定 `Style="{StaticResource SearchBarExtend}"`
![image](https://github.com/user-attachments/assets/e3203ec2-d87a-4715-b70a-3b3607c313d0)
