### ISSUE TITLE
DataGrid中的文本段落，设置允许折行时，Cell不能自适应高度

### ISSUE THREAD

**Issue by MichaelEdson** [NaBian/HandyControl#1660]
### Describe the bug

新建一个DataGrid，其中某列使用TextBlock显示长文本，该TextBlock设置TextWrapping属性为"Wrap"，实际效果确实有折行，但是单元格高度固定无法自适应，该问题在3.2.0版本没有出现，在后续版本直到最新的3.5.1上都有问题。

### Steps to reproduce the bug

1、新建一个DataGrid。
2、新增一列用于文本显示，添加一个TextBlock。
3、设置TextBlock的TextWrapping属性为"Wrap"。
4、为TextBlock的Text属性绑定一个长文本。
5、编译运行。

### Expected behavior

期待能够在折行的情况下，Cell高度自适应。

### Screenshots
正常的效果，3.2.0版本是正常的：
![PixPin_2024-10-17_10-42-32](https://github.com/user-attachments/assets/c7901f66-272a-467d-af99-f1032f09080f)

有问题的效果，3.2.0直到3.5.1有该问题：
![PixPin_2024-10-17_10-43-31](https://github.com/user-attachments/assets/e1e3ed7f-3030-4662-a95d-7dc808d21f87)

### NuGet package version

HandyControl 3.3.0

### IDE

Visual Studio 2022

### Framework type

.Net Framework 4.8

### Windows version

Windows 11 (22000)

### Additional context
示例代码：

                <DataGridTemplateColumn Width="100" Header="testText">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <TextBlock Text="{Binding Detail}" TextWrapping="Wrap" />
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>
                <DataGridTextColumn

_No response_

**Comment by Ling0925** [comment]
把RowHeight设置成NaN似乎可以？
```
 <DataGrid
     ...
     RowHeight="NaN">
</DataGrid/>
```
![image](https://github.com/user-attachments/assets/367fa7f6-4491-4fe0-9b85-33dcd37afe4b)

**Comment by Ling0925** [comment]
> 把RowHeight设置成NaN似乎可以？
> 
> ```
>  <DataGrid
>      ...
>      RowHeight="NaN">
> </DataGrid/>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/67010066/386032077-367fa7f6-4491-4fe0-9b85-33dcd37afe4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTU0NDQsIm5iZiI6MTczMTU1NTE0NCwicGF0aCI6Ii82NzAxMDA2Ni8zODYwMzIwNzctMzY3ZmE3ZjYtNDQ5MS00ZmUwLTliODUtMzNkY2QzN2FmZTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzMzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTVhNjBhMDZmZDYzMTgxZDgzMjRkOGE5YzQyNzY3ZDI3NWViODg0NDA5NTRkNWM4MDYzYzFiZjYwZWI1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QsJrnWCs-2r3TCvDZGo6yuIj1KStLrY1eyfqqVr84kM)

修改过后的DataGrid
```xaml
 <DataGrid
     hc:DataGridAttach.ShowRowNumber="True"
     AutoGenerateColumns="False"
     HeadersVisibility="All"
     ItemsSource="{Binding DataList}"
     RowHeaderWidth="60"
     RowHeight="NaN">
     <DataGrid.Columns>
         <DataGridTemplateColumn Width="60" CanUserResize="False">
             <DataGridTemplateColumn.CellTemplate>
                 <DataTemplate>
                     <Image
                         MaxWidth="32"
                         MaxHeight="32"
                         Source="{Binding ImgPath}"
                         Stretch="Uniform" />
                 </DataTemplate>
             </DataGridTemplateColumn.CellTemplate>
         </DataGridTemplateColumn>
         <DataGridTextColumn Binding="{Binding Name}" Header="{ex:Lang Key={x:Static langs:LangKeys.Name}}" />
         <DataGridCheckBoxColumn
             Width="100"
             Binding="{Binding IsSelected}"
             CanUserResize="False"
             Header="{ex:Lang Key={x:Static langs:LangKeys.Selected}}" />
         <DataGridComboBoxColumn
             Width="100"
             CanUserResize="False"
             Header="{ex:Lang Key={x:Static langs:LangKeys.Type}}"
             ItemsSource="{Binding Source={StaticResource DemoTypes}}"
             SelectedValueBinding="{Binding Type}" />
         <DataGridTextColumn Binding="{Binding Remark}" Header="{ex:Lang Key={x:Static langs:LangKeys.Remark}}" />
         <DataGridTemplateColumn>
             <DataGridTemplateColumn.Header>
                 <TextBlock Text="{ex:Lang Key={x:Static langs:LangKeys.Remark}}" />
             </DataGridTemplateColumn.Header>
             <DataGridTemplateColumn.CellTemplate>
                 <DataTemplate>
                     <TextBlock
                         MaxWidth="50"
                         Text="{Binding Remark}"
                         TextWrapping="Wrap" />
                 </DataTemplate>
             </DataGridTemplateColumn.CellTemplate>
         </DataGridTemplateColumn>
     </DataGrid.Columns>
 </DataGrid>
```

**Comment by MichaelEdson** [comment]
感谢@Ling0925，已确认设置RowHeight="NaN"确实有效，可能是新版区别于旧版的特性？
再次感谢！

**Comment by Ling0925** [comment]
在一次提交里面，默认的RowHeight被设置为了44，但我修改源码去掉这一行并没有变化 :( ，可能是还有其他的样式影响了
https://github.com/HandyOrg/HandyControl/commit/b7e08aec23017a13c34f7e72f4c8f75008be26bd#diff-11cb47e71e25222843d908b79618728755f0ae35e0183d73b2bb665097dc96bcR261

**Comment by MichaelEdson** [comment]
可能是设置最小高度影响了这个自适应效果吗，目前稍微有点拧巴的就是想开启自动高度的效果，设置的属性不是很符合直觉。
比如我一开始琢磨着把控件的高度设置为自动，或者设置文本折叠后高度应该能自适应（因为宽度固定了，并且开启文本换行），各种尝试确实没试出来。
这个设置Height为NaN来生效让我有点意外，以前没有这样赋值过，我这边应该是解决了，挺高兴的，不知道还有没有哪个兄弟仍然在努力地尝试解决同样的问题，哈哈。
最后感谢大佬的贡献和协助！
